### ISSUE TITLE
Mapbox-gl-draw no longer works in maplibre v3.0.0

### ISSUE THREAD

**Issue by erikvullings** [maplibre/maplibre-gl-js#2601] opened 2023-05-26 15:53 UTC
**maplibre-gl-js version**: 3.0.0

**browser**: Edge

### Steps to Trigger Behavior

 1. Go to your own [example](https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/)
 2. Note that the drawing tools, which are shown in the example gallery, are no longer there (probably, they have become very small in the top-right).
 3. Even when visible, the draw controls no longer react on mouse click events.

### Link to Demonstration

You can use your own [jsfiddle](https://jsfiddle.net/api/post/library/pure) to have a demo.

### Expected Behavior

I can draw on the map.

### Actual Behavior

Nothing happens.

**Comment by neodescis** [comment] 2023-05-26 17:19
I believe this is because MapLibre no longer has the Mapbox CSS classes applied. Mapbox Draw depends on them being there, and not just for CSS. There are checks in the Mapbox Draw code for them as well.

**Comment by neodescis** [comment] 2023-05-26 18:08
I've been able to work around the issue by adding the Mapbox classes back. Here's what I did.

First, add the Mapbox CSS classes to the MapLibre map:
```
// MapboxDraw requires the canvas's class order to have the class 
// "mapboxgl-canvas" first in the list for the key bindings to work
map.getCanvas().className = 'mapboxgl-canvas maplibregl-canvas';
map.getContainer().classList.add('mapboxgl-map');
const canvasContainer = map.getCanvasContainer();
canvasContainer.classList.add('mapboxgl-canvas-container');
if (canvasContainer.classList.contains('maplibregl-interactive')) {
  canvasContainer.classList.add('mapboxgl-interactive');
}
```

Also, when the draw controls are created, the MapLibre classes need to be added to what MapboxDraw creates:
```
const originalOnAdd = draw.onAdd.bind(draw);
draw.onAdd = (map) => {
  const controlContainer = originalOnAdd(map);
  controlContainer.classList.add('maplibregl-ctrl', 'maplibregl-ctrl-group');
  return controlContainer;
};
```

**Comment by HarelM** [comment] 2023-05-26 18:17
I'll close this issue as this is not a msplibre-gl bug. 
You can use the css from before version 3 asv it has both css classes, it might also have some stuff missing.

**Closed by HarelM** 2023-05-26 18:17 UTC

**Comment by neodescis** [comment] 2023-05-26 18:22
So... by closing this, are you saying that MapLibre no longer wants to support MapboxDraw at all? That seems strange to me, as does leaving a broken demo/example.

**Comment by HarelM** [comment] 2023-05-26 18:26
You have it backwards 😀
I can't force mapbox draw to support maplibre 3.0.
I have no control over their codebase.
If someone would like to contribute a fix there it would be great, but I can't track it here, it's not the right place...

**Comment by HarelM** [comment] 2023-05-26 18:39
I think that historically mapbox draw did make an effort to support maplibre.
There were talks about forking, but I don't know where it landed.
I agree that mapbox draw is an important capability for the community.

**Comment by joekrill** [comment] 2023-06-21 00:25
> You have it backwards 😀
> I can't force mapbox draw to support maplibre 3.0.
> I have no control over their codebase.

This problem was actually triggered by a change that _`maplibre`_ made, though - _not_  a `mapbox-gl-draw` change. The code in question on the `mapbox-gl-draw` side of things has been that way for 4+ years -- before maplibre even existed. I suppose it could be argued that they shouldn't have [hard-coded the class names in their codebase](https://github.com/mapbox/mapbox-gl-draw/blob/02c5e798377db6f11e73566450dbaad6963f11f4/src/constants.js#LL2C8-L2C8) in the first place, but at the time there was no reason to not do that. 

So ultimately it was really #1575 that "broke" this, I believe. 

I can totally understand this project not wanting to include the `mapbox-gl-js` classes. But it may be worth reconsidering that decision to maintain as much compatibility as possible and avoid alienating users who might otherwise switch.

> If someone would like to contribute a fix there it would be great, but I can't track it here, it's not the right place...

I will try to get a PR up for `mapbox-gl-draw` and see how it goes over there. But there's likely other plugins that are going to break in similar ways. 

In the meantime another option that may work for some folks is adding this code somewhere:

```ts
import MapboxDraw from "@mapbox/mapbox-gl-draw";

// @ts-ignore
MapboxDraw.constants.classes.CONTROL_BASE = "maplibregl-ctrl";
// @ts-ignore
MapboxDraw.constants.classes.CONTROL_PREFIX = "maplibregl-ctrl-";
// @ts-ignore
MapboxDraw.constants.classes.CONTROL_GROUP = "maplibregl-ctrl-group";
```

This worked for me for _most_ functionality, but there's still some CSS rules that rely on the `.mapboxgl-map` and other mapbox-specific class names.

**Comment by neodescis** [comment] 2023-06-21 16:43
I agree with @HarelM that it would be great for plugins to be updated to work with both, but I'm not sure how feasible that is. MapboxDraw still hasn't published [my pull request](https://github.com/mapbox/mapbox-gl-draw/pull/1165) for a compatibility fix with MapLibre 2.x that got merged three months ago...

**Comment by erikvullings** [comment] 2023-06-22 07:24
@joekrill @neodescis Thanks for your feedback! Since drawing is quite an essential feature for a map library IMHO,, would it make sense to you to merge the MapboxDraw functionality into MapLibre, so this kind of functionality remains under control? Preferably allowing for tree shaking, so it would only be included in the final bundle when required.

**Comment by HarelM** [comment] 2023-06-22 07:34
Tree shaking is a painful point.
And unfortunately, I don't agree that this component is essential for a map library as it is very opinionated and specific...
If the library is not well maintained and someone would like to maintain it under maplibre organization it would be great, much like other plugins and wrappers.

**Comment by HarelM** [comment] 2023-06-27 19:31
@stepankuzmin is there a chance to release a new version of mapbox-gl-draw? I see that the linked PR was merged and should help here, wouldn't it?
There is a new issue reported once a week about mapbox-gl-draw not working with maplibre 3.0 roughly.
I think that in the linked issues here there are good people that might be able to help maintain mapbox-gl-draw.
I really think that forking should be the last resort and I'm not sure we are there yet...

**Comment by stepankuzmin** [comment] 2023-06-28 09:50
Hey everyone! Yes, I planned to cut a GL Draw release, but I was caught up with some stuff. I'll find some time to make a release.

**Comment by stepankuzmin** [comment] 2023-06-28 12:51
@HarelM Published `@mapbox/mapbox-gl-draw` v1.4.2 https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.4.2

**Comment by HarelM** [comment] 2023-06-28 12:57
THANKS!! I'll update the docs within a few weeks.

**Comment by neodescis** [comment] 2023-06-29 22:26
Yes, thanks a bunch @stepankuzmin! @HarelM, keep in mind my fix was to get MapboxDraw working with MapLibre 2.x. Much of what I posted above is still needed for 3.x. I'm more than willing to work on MapboxDraw to get it working with 3.x, but probably we'll need to discuss an approach. I can file an issue in that repo and mention this one to get the ball rolling.

**Comment by bk201lucifer** [comment] 2023-08-01 02:47
I have made the following modifications and can run normally
![a](https://github.com/maplibre/maplibre-gl-js/assets/63433257/eda38bde-7995-4690-840a-3400b854926e)

**Comment by HarelM** [comment] 2023-08-01 05:30
@bk201lucifer can you open a PR to update the example here in this repo with these changes?

**Comment by nitrag** [comment] 2023-08-01 20:39
I can confirm that changing the constants fixes the issue.

```
MapboxDraw.constants.classes.CONTROL_BASE = "maplibregl-ctrl";
MapboxDraw.constants.classes.CONTROL_PREFIX = "maplibregl-ctrl-";
MapboxDraw.constants.classes.CONTROL_GROUP = "maplibregl-ctrl-group";
```

**Comment by HarelM** [comment] 2023-08-03 17:16
We can update the example, and later on update it again.
Better something than nothing I think...

**Comment by kevinjmo** [comment] 2023-12-05 23:15
Regarding the resolution, is the fix for us to add these three lines in our project before the MapboxDraw instance?

https://github.com/OpenRadioMap/maplibre-gl-js/blob/a9ffa1795f131d1545fb7f35c29ce1f632517b6d/test/examples/mapbox-gl-draw.html#L49-L51

The changes in #3394 seem to only update the example HTML, and doesn’t add anything to the actual `maplibre-gl-js` code itself.

**Comment by HarelM** [comment] 2023-12-06 08:28
There shouldn't be any code changes in maplibre-gl-js as mapbox-gl-draw is a plugin and should facilitate for these issues.
Your best approach would be to open a PR in the mapbox-gl-draw repo to solve these issues.
