### ISSUE TITLE
webgl1 support and future

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2653] opened 2023-06-09 16:48 UTC
## User Story

Closely related to #2644 
I'd like to suggest keep webgl1 support for much longer period of time

## Rationale
**Fact 1:**
With an one-day experiment on Bing users with MapLibre 3.0.1 release, the error rate of unable to create webgl context increased 9 times from 0.14% to 1.3%.
Put into context, right now there are total of 1.2 million user sessions per day, and a new feature is being released to bring 9x more sessions to MapLibre.

In short, 10 million sessions per day are expected and 1.3% of that --- about 140K sessions would fail if webgl1 was removed.

It appears that the hardware situation of end consumers is not ready for this limitation. Not to mention enterprise customers who tend to be even slower to upgrade.

**Fact 2**
Webgl (1 or 2) itself is sunsetting, sadly, and being superseded by webgpu. 
Sure the process can take many years, but the trend is irreversible. Therefore, the investments on webgl2 only features and optimizations might not get the best return after all

## Suggestion
1) In short term restore the support of webgl1
2) In long term, invest more on flexible render subsystems: webgl1 and 2 and maybe webgpu, so the "upper part" can be easily plugged into any combination of the other three.
It is perfectly aligned with our bounty direction https://github.com/maplibre/maplibre/issues/273
#2606 

Thanks

**Comment by birkskyum** [comment] 2023-06-10 02:56
Thank you for the writeup, and the real-life test data - it's very valuable as always.

Regarding this bullet:

> Sure the process can take many years, but the trend is irreversible. Therefore, the investments on webgl2 only features and optimizations might not get the best return after all

The short- and long-term benefits to investing in webgl2 is that we can refactor the code in ways that will make it faster short-term by i.e. adopting uniform buffer objects, and when WebGPU eventually arrives it will make adoption easier because it has a similar concept.

We will of course consider this inquiry carefully, and it will be on the TSC agenda on Wednesday 14th June, but keep in mind that there also is a prioritization of resources taking place here. Our budget currently allow for just one part-time maintainer, and it puts certain restraints on our ability to serve the marginal 1% of users while also pushing the project forward in ways that can benefit the other 99%. We're in the process of raising more funds to better the situation.

**Comment by zhangyiatmicrosoft** [comment] 2023-06-10 03:40
Thank you for the insights. I'd suggest investing more on https://github.com/maplibre/maplibre/issues/273 and it will be win-win for everybody --- so that it is flexible enough to swap back and forth.
Also don't think it is just 1% users though --- it is significant enough to stop us from upgrading to 3.0.1.
Having seen many companies, from 10 people startup to multibillion corps, I'd boldly say from web app owner point of view, it is usually not justified to ignore 1% to move forward to a new version. :)

**Comment by HarelM** [comment] 2023-06-10 05:37
Two things to consider here:
1. I'm not sure this is actually a different issue than #2644, so it seems we are talking about the issue in two different places. I suggest to close this issue and move the discussion to the above issue.
2. Much like other features that are needed by companies, I think the way forward would be to implement what you need on your end and contribute it back. My main concern here though is that it will be very hard to keep the bundle size small while supporting both webgl 1 2 etc. I'm having a hard time imagining how it can be a pluggable option knowing how this library works and the way it is bundled, but I'll be happy to learn 😀

**Comment by birkskyum** [comment] 2023-06-12 08:17
Would it be viable to load 3.x or 2.4 depending on the webgl2 hardware support as suggested in the #2644 ?

**Comment by HarelM** [comment] 2023-06-12 12:00
It's possible if you don't use a build system such as rollup or webpack I believe. Which is not the case in most modern sites.

**Comment by birkskyum** [comment] 2023-06-12 12:56
Right, so adding the fallback is actually the only solution that can be deployed in a reasonable timeframe (in contrast to the lightweight renderers) without creating other immediate regressions (such as giving up bundler compatibility or the webgl2 context). @zhangyiatmicrosoft , if possible it would be a great help if your team can help us monitor to what extend the webgl1 fallback is used, and if it appear to be obsolete at some point.

**Closed** 2023-06-12 13:08 UTC

**Comment by birkskyum** [comment] 2023-06-13 21:31
@jsehner , @HandyMenny, @pramilk , @zhangyiatmicrosoft  Thanks for raising awareness. WebGL1 fallback added in newly released v3.1.
