### ISSUE TITLE
Source exists but not listed in style after re-adding

### ISSUE THREAD

**Issue by rsimon** [maplibre/maplibre-gl-js#3596] opened 2024-01-19 11:25 UTC
Hi,

I'm using the [following approach to change the map baselayers](https://docs.mapbox.com/mapbox-gl-js/example/style-switch/) while keeping my data layers.

I'm running into the following problem:
- After I re-add my sources and data layers, `map.getStyle().sources` lists the re-added sources and layers correctly
- Later, elsewhere in my application, the source is no longer available
   - `map.getStyle().sources` does __not__ list the source
   - Trying to re-add the source at this point throws the error `Error: Source "my-data-source" already exists.`

I.e. it seems that the layer is there, but somehow not being exposed in `getStyle().sources`.

**maplibre-gl-js version**: 3.6.2

**browser**: Chrome

**Comment by neodescis** [comment] 2024-01-19 15:53
Can you please provide a minimal reproduction of the issue?

**Comment by rsimon** [comment] 2024-01-19 16:36
I'll try to set one up if I get the chance. But a simple one I tried (as usual...) didn't show the behavior, so I need to put together a fuller one. For context: 
- I'm storing my map instance in a React context
- I'm updating sources/layers in one component
- Another component accessing the same instance experiences the issue (= source not listed in `map.getStyle().source`, but re-adding the source throws `Error: Source ... already exists`.

Meanwhile, I worked around the issue be not removing/re-adding the sources, but updating the style directly. This works with no problems.

In case it helps - here's the modified code that works: 

```
const updated = {
  ...style, // Current style
  layers: [
    // List of next base layers
    ...next.layers,
    // IDs of layers to keep from the current style are in a Set<string>
    ...style.layers.filter(l => layerIdsToKeep.has(l.id))
  ],
  sources: Object.fromEntries([
    // Next base layer sources
    ...Object.entries(next.sources),
    // Current sources to keep
    ...Object.entries(style.sources).filter(([id, _]) => sourceIdsToKeep.has(id));
  ])
} as StyleSpecification;

map.setStyle(updated);
```

Here's the code I used before, which lead to the reported issue:

```
// Change the style to the next set of baselayers,
// erasing all data layers
map.setStyle(next);

const onStyleLoaded = () => {
  sourcesToKeep.forEach(([id, source]) => map.addSource(id, source));
  layersToKeep.forEach(layer => map.addLayer(layer));
}
  
map.once('styledata', onStyleLoaded);
```

**Comment by neodescis** [comment] 2024-01-19 16:48
At least part of the problem you experienced is because the "styledata" event can be fired multiple times for a single style change. Also, unfortunately, it is often last fired before map.isStyleLoaded() returns true. In my own project, I am handling this by waiting for "styledata" events and then checking for map.isStyleLoaded() to return true, in a setInterval() callback if it doesn't return true right away.

Another workaround is to set `diff: false` when calling setStyle, at which point the "style.load" event can be used instead.

**Comment by rsimon** [comment] 2024-01-19 16:52
Ah, thanks for this explanation! The `.once()` listener makes sure my handler gets executed only once. But that, obviously, would be at the time the first `styledata` event arrives, so I can see that this might be a problem. (I wasn't aware of the `isStyleLoaded()` check.)

Anyways, I feel that the current solution is nice, anyway. Also, visually, it keeps my data layers mounted while only the background changes. So I'll probably stick to that solution.

**Comment by neodescis** [comment] 2024-01-19 17:07
Sounds good. I'm going to go ahead and close this, but feel free to re-open if needed.

**Closed by neodescis** 2024-01-19 17:07 UTC
Labels: need more info
