### ISSUE TITLE
ERROR: "build-dev" exited with 1

### ISSUE THREAD

**Issue by nicky132** [maplibre/maplibre-gl-js#3304] opened 2023-11-02 03:57 UTC
**maplibre-gl-js version**:3.5.2

**browser**:版本 118.0.5993.118（正式版本） （64 位）

### Steps to Trigger Behavior

 1.npm install
 2.npm run build-dist
 3.ERROR: "build-dev" exited with 1.

`[!] (plugin typescript) RollupError: @rollup/plugin-typescript TS2322: Type 'Mock<Promise<Response>, [_input: URL | RequestInfo, _init?: RequestInit], any>' is not assignable to type '{ (input: URL | RequestInfo, init?: RequestInit): Promise<Response>; (input: RequestInfo, init?: RequestInit): Promise<...>; }'.`

`[!] (plugin typescript) RollupError: @rollup/plugin-typescript TS2322: Type 'Mock<Promise<Response>, [_input: URL | RequestInfo, _init?: RequestInit], any>' is not assignable to type '{ (input: URL | RequestInfo, init?: RequestInit): Promise<Response>; (input: RequestInfo, init?: RequestInit): Promise<...>; }'.`

### Expected Behavior
npm run build-dist works
### Actual Behavior

![1698897456301_2D21D500-6A4A-40a6-A627-D746C62152B4](https://github.com/maplibre/maplibre-gl-js/assets/34881461/ed414b18-c89e-418e-8563-5322cd0f7ae5)

![1698897429456_B7AB2D57-F91F-494f-BC16-566A66E754CC](https://github.com/maplibre/maplibre-gl-js/assets/34881461/12ff7fbf-ffd9-4cae-a54a-1aecf7843cf0)

**Comment by HarelM** [comment] 2023-11-02 05:25
Duplicate of #3303 
The build is constantly passing CI, on entry major platform.
please make sure you are using the right now version (18).

**Closed by HarelM** 2023-11-02 05:25 UTC
