### ISSUE TITLE
Add Data-driven property specification to line-dasharray

### ISSUE THREAD

**Issue by kboyd-fb** [maplibre/maplibre-gl-js#2261] opened 2023-03-09 21:41 UTC
## User Story

As a software engineer I can use feature properties to customize the [line-dasharray](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#paint-line-line-dasharray) property on line layers, so that users of my application can have more in depth customization features on their map.

## Rationale

- The types say that this is a data-driven property specification 
```
"line-dasharray"?: PropertyValueSpecification<Array<number>>;
```
- Without this, line layers are limited in terms of style customization. 
- Dashed lines are often used in CAD and other forms of diagrams to dictate different states of lines.
- This has already been implemented by Mapbox GL JS. https://github.com/mapbox/mapbox-gl-js/pull/10591

## Impact

- Users that want to customize this property need to add individual layers with different line-dasharray properties, and filter each layer's visible features to those which should show in that style

Any information on if this would be possible, or if there exist any work arounds would be greatly appreciated.

**Comment by HarelM** [comment] 2023-03-09 22:12
I think this is a good addition.
A small note, the current typings do not suggest that this is a data driven property.
Also note that mapbox code that implemented this is not open in terms of license and we should not copy it.

**Comment by wipfli** [comment] 2023-03-28 20:45
If you have not already done it, you can give this bounty direction an upvote: https://github.com/maplibre/maplibre/discussions/167

**Comment by 1ec5** [comment] 2023-08-14 14:41
Duplicate of #1235?

**Comment by HarelM** [comment] 2023-08-14 15:29
Yup. Closing.

**Closed by HarelM** 2023-08-14 15:29 UTC
Labels: enhancement, PR is more than welcomed
