### ISSUE TITLE
With terrain no redraw when setting layer visibility to false or changing opacity

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1461] opened 2022-08-11 07:27 UTC
Version 2.2.0-pre3 with a terrain specified:

No (full) redraw is triggered, when a layer's visibility is set to false - only when moving the map or zooming, the map is updated.
* raster tiles, e.g. osm: no redraw without move/zoom
* vector tiles: the labels are removed immediately, the rest only after move/zoom

Also, no redraw is triggered, when the opacity ("fill-opacity", etc.) changes ("hillshade-exaggeration" works). Only the opacity of labels is updated without move/zoom.

A simple click on the map seems to work, too (not always).
When zooming (mouse wheel) the no longer visible layer is only removed after some significant zooming.

Calling map.redraw() after setting the visibility property to "none" does not improve the situation.

**Comment by HarelM** [comment] 2022-08-11 07:55
This is only relevant when terrain is on, right?

**Comment by HarelM** [comment] 2022-08-11 07:56
P.S. we just released version 2.2 as an official version yesterday.

**Comment by cns-solutions-admin** [comment] 2022-08-11 08:10
I'll try the new version.

**Comment by cns-solutions-admin** [comment] 2022-08-11 08:27
No changes in 2.2.0.
Changes to visibility and xxx-opacity do not update the map (except labels).

**Comment by HarelM** [comment] 2022-08-11 08:55
> This is only relevant when terrain is on, right?

?

**Comment by cns-solutions-admin** [comment] 2022-08-11 09:02
Yes, as the title says: only with terrain. But it does effect the whole map, not just the part, where there is terrain.

**Comment by prozessor13** [comment] 2022-08-11 11:12
Can you please test your issue with this pull request? https://github.com/maplibre/maplibre-gl-js/pull/1301

**Comment by cns-solutions-admin** [comment] 2022-08-11 13:02
No change with #1301. Does still not update the map.

**Comment by cns-solutions-admin** [comment] 2022-08-22 14:47
Correction regarding #1301 (it was using some cached version before): it flickers, but it works!

However, when loading the map, tiles seem to be drawn at the wrong positions (e.g. the hillshade/3d tile of Innsbruck is drawn in all tiles) - it seems that every tile is drawn at every possible position, but at the end everything looks fine.
When switching off a layer (visibility), something similar happens, e.g. the hillshade/ed tile of Innsbruck very briefly shows (at least) in eastern europe.

**Comment by prozessor13** [comment] 2022-08-23 13:57
Hello,

can you please create an, as simple as possible, test-page, so i can reproduce and test the issue?

**Comment by cns-solutions-admin** [comment] 2022-08-23 14:55
Switching off the OSM layer does not update the map: https://jsfiddle.net/martinatcns/c91br8tv/59/

**Comment by prozessor13** [comment] 2022-08-24 08:26
Thx for demo. I made a new checkin in https://github.com/maplibre/maplibre-gl-js/pull/1301. Can you please test the new commit?

**Comment by prozessor13** [comment] 2022-08-24 13:38
Can you please post your (simplified) Stylesheet somewhere?

**Comment by cns-solutions-admin** [comment] 2022-08-24 15:56
See the code at https://jsfiddle.net/martinatcns/4uvtp3rc/5/
* the landcover and road layers are copies from https://api.maptiler.com/maps/streets/style.json?key=your_key
* if executed with maplibre built from your branch, the landcover layer and the road layer won't immediately show, when switched on.
* you will need your own api.maptiler.com key, if you execute it locally.

**Comment by acalcutt** [comment] 2022-08-24 16:21
I tested your example and see what you mean. 

- with the default "Terrain On", only the hillshade layer toggles. however you can see attribution disappears, like it was actually toggled.
- with "Terrain Off" all the layers toggle off and on fine.

**Comment by prozessor13** [comment] 2022-08-31 08:24
I did another checkin in the PR, but still no success at all. I think the render-logic is correct now, but layers are still not visible because of some transition things going on. Tried a lot without success. Maybe another day is a better day...

**Comment by prozessor13** [comment] 2022-08-31 09:31
Finally found the issue. ufff. Can you please test?

**Comment by cns-solutions-admin** [comment] 2022-08-31 11:33
Unfortunately with the newest rtt_rerender_on_style_change branch it got rather worse:
* no immediate changes at all, when switching on/off a (non hillshade) layer
* it seems that tiles are never removed, e.g. 
** switch off OSM => no immediate change
** zoom in some => OSM not shown
** zoom out again => OSM shown

**Comment by prozessor13** [comment] 2022-08-31 12:08
Hmm strange, with my test page all works as expected, are you sure you did a correct build?

To test with my page please use:
https://github.com/maplibre/maplibre-gl-js/pull/1301/files#diff-157c62909dec6a9a1f2acfb30c79ffd7a7a4e4a35ac9c67f25fe0527a00a0f15

Dont forget to replace the `XXXXX` with our maptiler api-key.

**Comment by cns-solutions-admin** [comment] 2022-08-31 13:40
You are right, I had somehow used an old version.
Toggling layers now works perfectly.

And even better, with our full application, it seems that (compared to 2.4.0):
* GPU memory usage is greatly reduced: 4GB instead of 16+GB and crashing
* frame rate is much better

Can you confirm that this might be caused by your change?

**Comment by prozessor13** [comment] 2022-08-31 13:54
Hmm, i think this PR should have no big impact on performance, may you changed your stylesheet? The arrangement of layers can have a huge impact on performance. see: https://github.com/maplibre/maplibre-gl-js/issues/1368

So, i close this issue!

**Closed** 2022-08-31 13:54 UTC
Labels: bug, PR is more than welcomed, Terrain 3D
