### ISSUE TITLE
Globe rotation is limited when terrain layer is used

### ISSUE THREAD

**Issue by sebstryczek** [maplibre/maplibre-gl-js#5115] opened 2024-11-25 13:54 UTC
**maplibre-gl-js version**: 5.0.0-pre.7

**browser**: Chrome Version 131.0.6778.86 (Official Build) (x86_64) (MacOS, Intel)

### Steps to Trigger Behavior

 1. Add terrain source..
 2. Set projection to `globe`.
 3. Set zoom to low value (~2, to see whole globe).
 4. Start panning (rotating the globe).

### Link to Demonstration

https://jsbin.com/bipohuqapo/edit?html,js,output

### Expected Behavior

Globe rotation should be possible continuously in all directions, allowing for infinity movement without hitting a stopping point.
Globe rotation should be working the same way with and without terrain layer.

### Actual Behavior

Globe rotation is possible only to specific point.
Works fine without terrain.

https://github.com/user-attachments/assets/9400145a-df69-40a4-b58b-26cb126e4ed0

**Comment by zerda-ocm** [comment] 2024-11-25 14:12
Duplicate of #5009

**Closed** 2024-11-25 14:16 UTC
Labels: bug, PR is more than welcomed, terrain, globe
