### ISSUE TITLE
map.setTerrain() incompatible with a style with several Hillshade layers

### ISSUE THREAD

**Issue by lstiz** [maplibre/maplibre-gl-js#1372] opened 2022-07-13 08:40 UTC
If you try to setTerrain() and a style with several Hillshade layers, the map does not work properly. 
I have several hillshades with different zoom ranges for each one --> not work. 
I tried to pass a "visibility": none prop., --> not work  
Only works if I left **only one layer** with type Hillshade.

**Comment by HarelM** [comment] 2022-07-13 09:42
The issue you have reported here is not clear.
Can you please elaborate?
Also sounds like an exiting issue related to terrain 3D, can you check with the existing issues labeled with terrain 3d if there's something similar?

**Comment by prozessor13** [comment] 2022-07-15 06:38
Hello,

i think the problem ist somewhere around this: https://github.com/maplibre/maplibre-gl-js/blob/main/src/render/render_to_texture.ts#L135 .
To this issue there is a performance-question. When rendering-to-texture all layers which can combined are rendered into one texture (fill, line, background, raster, called stacks in `renderLayer`), but because of light the hillshading-layer is rendered into a separate texture every camera movement, so multiple hillshading layers are rendered into multiple textures. I think this is slow. So the hillshading layers should be stacked as well. I think writing tests for this is mandatory.
Currently i am on vacation, so i look further into this in one month or so.

**Comment by HarelM** [comment] 2023-03-04 18:56
@lstiz is this still and issue?
Can you please share a jsbin or something similar to illustrate this issue?

**Comment by HarelM** [comment] 2023-11-19 15:58
No extra info was provided. Closing this for now, if this is still relevant please add more info and I'll be happy to re-=open it.

**Closed by HarelM** 2023-11-19 15:58 UTC
Labels: bug, PR is more than welcomed, need more info, Terrain 3D
