### ISSUE TITLE
Supported browsers? Please add to readme.

### ISSUE THREAD

**Issue by hheexx** [maplibre/maplibre-gl-js#920] opened 2022-01-31 15:57 UTC
I have some issues with safari 14. is it supported?

Error: out of range source coordinates for image copy
  at invoke(webpack:/./node_modules/maplibre-gl/dist/maplibre-gl.js:31:7831)

**Comment by wipfli** [comment] 2022-01-31 16:25
Thanks for reporting. Can you share a stackblitz?

**Comment by xabbu42** [comment] 2022-02-02 10:12
Maybe a duplicate of #575?

**Comment by wipfli** [comment] 2022-02-04 09:07
I wonder if we need to fork https://github.com/mapbox/mapbox-gl-supported?

**Comment by wipfli** [comment] 2022-02-04 09:09
I wonder why Mapbox factored this out as a package... https://github.com/mapbox/mapbox-gl-supported/blob/gh-pages/index.js could also be part of the MapLibre GL JS library.

**Comment by HarelM** [comment] 2022-02-04 09:50
I guess it is used in several libraries...
But we might move it in, it's a very small piece of code...

**Comment by xabbu42** [comment] 2022-02-04 10:18
one could want to test for maplibre-gl-js support with a lightweight library before loading the complete library. so we should still generate a separate file one can include with only that functionality.

**Comment by wipfli** [comment] 2022-02-04 10:39
I'm happy to prepare a fork of https://github.com/mapbox/mapbox-gl-supported.

**Comment by wipfli** [comment] 2022-02-04 16:52
https://github.com/maplibre/maplibre-gl-js/blob/31d79b6330927253b87395906ce1b99477e15436/package.json#L17

shows that we use mapbox-gl-supported.

**Comment by wipfli** [comment] 2022-02-04 16:54
@hheexx you can check if a browsers supports MapLibre GL JS with:

```js
// Show an alert if the browser does not support MapLibre GL
if (!maplibregl.supported()) {
  alert('Your browser does not support MapLibre GL');
}
```

For the full documentation, see: https://maplibre.org/maplibre-gl-js-docs/api/properties/#supported

**Closed by wipfli** 2022-02-04 16:54 UTC

**Comment by wipfli** [comment] 2022-02-04 19:13
Great, thanks!

**Comment by hheexx** [comment] 2022-02-14 21:10
@wipfli  Property 'supported' does not exist on type 'typeof import("/ClientApp/node_modules/maplibre-gl/dist/maplibre-gl")'.ts(2339)
