### ISSUE TITLE
maxzoom for StyleLayer differs from maxZoom for Map

### ISSUE THREAD

**Issue by nickpeihl** [maplibre/maplibre-gl-js#1549] opened 2022-08-25 21:22 UTC
The StyleLayer [hides the layer](https://github.com/maplibre/maplibre-gl-js/blob/d41b20399eb9548da0fcbc1a30b809245d5d3b00/src/style/style_layer.ts#L193) when the [`maxzoom`](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#maxzoom) is reached. However, the `Map` is still visible at the [`maxZoom` option](https://maplibre.org/maplibre-gl-js-docs/api/map/#map-parameters). 

For example, take a look at [this demo](https://codepen.io/nickpeihl/pen/yLKWzGN). The Map `maxZoom` and the layer  `maxzoom` are set to the same value. But as you zoom in to the `maxZoom` of the Map, the cat layer disappears. It seems to me that the layer should still be visible at the `maxzoom` rather than hidden. Is this by design?

**Comment by HarelM** [comment] 2022-08-26 05:30
Probably a different between < and <= as the cat is visible in zoom 2.999 but not in 3...
Not sure if this is by design or not...

**Comment by xabbu42** [comment] 2022-08-26 13:29
I think this is by design. 

It is important for style definitions that only one of maxzoom and minzoom include the border so that you can switch cleanly between two style definitions depending on zoom levels. For the map it is more important for maxZoom and minZoom to be consistent and do what you would expect. This two requirement together mean that we have to live with this inconsitency I'm afraid.

**Comment by HarelM** [comment] 2023-11-19 16:02
Closing, as work by design, if this is not sufficient, feel free to open another issue with a design proposal.

**Closed by HarelM** 2023-11-19 16:02 UTC
Labels: need more info
