### ISSUE TITLE
Cannot read property point of null - placeGlyphsAlongLine function

### ISSUE THREAD

**Issue by JacopoSciampi** [maplibre/maplibre-gl-js#153] opened 2021-05-04 08:38 UTC
**maplibre-gl-js version**: 1.14.0

**browser**: It doesn't matter.

### Steps to Trigger Behavior

 1. Having a lot of glyphs rendered at the same time
 2. Trigger the mapbox message "Too many glyphs rendered at the same time"
 3. Tilt the 3d map for a while
 4. You get the error in console

I can't really give a live example since I have no idea how the custom tiles are generated - I can ask tho.
this is anyway an image to let you understand the quantity of stuff those tiles have:

![image](https://user-images.githubusercontent.com/32507291/116978594-38b6be80-acc4-11eb-9572-865c807708e9.png)

Debugging for about 40 hours brought me to this conclusion:

The function `placeGlyphsAlongLine` execute this code:ù

```
...
for (var glyphIndex = symbol.glyphStartIndex + 1; glyphIndex < glyphEndIndex - 1; glyphIndex++) {
                    // Since first and last glyph fit on the line, we're sure that the rest of the glyphs can be placed
                    // $FlowFixMe
                    placedGlyphs.push(placeGlyphAlongLine(fontScale * glyphOffsetArray.getoffsetX(glyphIndex), lineOffsetX, lineOffsetY, flip, anchorPoint, tileAnchorPoint, symbol.segment,
                        lineStartIndex, lineEndIndex, lineVertexArray, labelPlaneMatrix, projectionCache));
                }
...
```

but sometimes the array gets populated with an entry: null as shown below:

![image](https://user-images.githubusercontent.com/32507291/116978541-22106780-acc4-11eb-81b1-ab4881afa186.png)

After the array gets populated, the code executed next is that: 

```
for (var i = 0, list = placedGlyphs; i < list.length; i += 1) {
        var glyph = list[i];
        performance.addDynamicAttributes(dynamicLayoutVertexArray, glyph.point, glyph.angle);
}

```

Since some glyphs are null this will fire the error as the title say.
Mapbox has the same behavior and what I did some months ago to "fix" that was to add a simply condition to that last snippet: 

```
for (var i = 0, list = placedGlyphs; i < list.length; i += 1) {
        var glyph = list[i];

        if (glyph) {
            if (!!glyph.point && glyph.angle) {
                performance.addDynamicAttributes(dynamicLayoutVertexArray, glyph.point, glyph.angle);
            }
        }
    }
```

Even if this edit "fix" the problem, I haven't undersatand why this happens.

Looking anywhere it seems that no one has ever had this problem so I'm pretty sure it's a problem related on how we generate the tiles and the custom objects in it, but why is this happening? The function `placeGlyphAlongLine` doesn't even return a null value, but rather an object: 

```
return {
        point: p,
        angle: segmentAngle,
        path: pathVertices
    };
```

I'm really confused.

*edit* 

I've discovered something that's strange to me.

![image](https://user-images.githubusercontent.com/32507291/117007922-77f80600-acea-11eb-921b-ab6a0ff5fe21.png)

it seems that the text - sometimes - it doesn't get rotated corretly and its get hided (maybe not removed) and this will fire the error. Testinng the rotation of the map with a tilt of almost 0° it does rotate the text correctly, but if I do the same thing with more tilt (ie ~30°) it doesn't work and the text disappear. If I keep rotating the map it'll appear again rotated.

**Comment by everhardt** [comment] 2021-12-22 08:56
I also see this error once in a while, I don't think it is solved.

**Comment by HarelM** [comment] 2021-12-22 09:32
A jsbin would help a lot here to try and see this error, or a PR with the relevant fix.
I tend to agree that simply checking for null is not a great solution as the problem is probably deeper somewhere.
I'll reopen nevertheless.

**Comment by everhardt** [comment] 2021-12-22 11:30
> The function placeGlyphAlongLine doesn't even return a null value, but rather an object

It can return `null`, at https://github.com/maplibre/maplibre-gl-js/blob/e78ad7944ef768e67416daa4af86b0464bd0f617/src/symbol/projection.ts#L382-L383

I have not identified a case that could cause that condition on line 382 to be true. In the stack trace from the error is see, `placeGlyphsAlongLine` is called by https://github.com/maplibre/maplibre-gl-js/blob/e78ad7944ef768e67416daa4af86b0464bd0f617/src/symbol/projection.ts#L197-L200

**Comment by gregorwebdev** [comment] 2022-06-03 06:18
Any news on this? I will simply do this:
    for (const glyph: any of placedGlyphs) {
        if (glyph) {
            addDynamicAttributes(dynamicLayoutVertexArray, glyph.point, glyph.angle);
        }
        
       is it harmful?

    }

**Comment by HarelM** [comment] 2022-06-03 14:24
It might be harmful from a performance stand point.
I would recommend better understanding the root cause as I said in my previous post.

**Comment by HarelM** [comment] 2022-08-17 12:38
Please share a reproduction. We can't debug an image...

**Comment by HarelM** [comment] 2023-11-19 15:36
No reproduction was shared, closing, if this is relevant in the future I'll be happy to re-open it.

**Closed by HarelM** 2023-11-19 15:36 UTC
Labels: bug, need more info
