### ISSUE TITLE
Feature id can only be positive integer when using feature-state

### ISSUE THREAD

**Issue by crooy** [maplibre/maplibre-gl-js#1043] opened 2022-03-03 19:08 UTC
**maplibre-gl-js version**: 2.1.6

**browser**: chrome

### Steps to Trigger Behavior

 1. create a geojson dataset (featureCollection with Features).
 2. The dataset I use is very simple just geopoints in Features with a uuid as id, and that same id in a property 
 3. I then use feature-state to set the "selected" property to true when clicking on the markers, and i reset it when clicking another marker. Using a case statement in the styling from one of the examples i want to change color for the dots i render.
 4. Now while debugging why it doesnt work, i found out the id's were empty. So i read up on the geojson spec, and indeed strings were allowed. I tried integers and it almost worked, only the first marker did not work, the one with 0 as id. 
 5.  I now give all markers positive integers as id and it works perfectly.

### Link to Demonstration

the broken version:
https://stackblitz.com/edit/typescript-kmywnn?file=index.ts

the working version:
https://stackblitz.com/edit/typescript-ese6ag?file=index.ts

note the differences in id string vs int

```
const features = [
 {
      'type': 'Feature',
      'properties': {    
        'posterId': this.id // tried uuids, later integers
      },
      'id': this.id,
      'geometry': this.location
},
...
]
const geodata =  {
    'type': 'FeatureCollection',
    'features': features
  }
...

  mapRef.addSource('my-layer', {
          type: 'geojson',
          data: geodata,
        });
mapRef.on('click', 'my-layer', function (e: MapLayerMouseEvent) {
        const myId = e?.features && e?.features[0]?.properties?.myId; // the uuid i was expecting
        const id = e.features?.[0].id // undefined
})
```

### Expected Behavior
I expected to get the uuid in the id, or the 0-integer.
I also expected the positive integers to work as id-values.

### Actual Behavior
i got undefined for string ids, undefined for 0
But i did get the positive integers back when used as id.

**Comment by HarelM** [comment] 2022-03-03 19:13
Can you please share a stackblitz/jsbin/code pen of the issue?
The code in this example has typos and missing context...

**Comment by crooy** [comment] 2022-03-04 07:05
the broken version:
https://stackblitz.com/edit/typescript-kmywnn?file=index.ts

the working version:
https://stackblitz.com/edit/typescript-ese6ag?file=index.ts

note the differences in id string vs int

**Comment by HarelM** [comment] 2022-03-04 09:25
You set `myId` in the feature and then look for `posterId` in the event? I'm a bit lost here...

**Comment by crooy** [comment] 2022-03-04 17:27
Sorry that line wasnt relevant, i tried to clean it from my actual code. i removed that line, it was not needed for this demo.

The demo's show that you can click on the dots in the one, and they will change color and size, and in the other it doesnt work. The only difference is (should be) the id being strings or positive integers.

**Comment by crooy** [comment] 2022-03-16 18:37
Ok, so i've adapter the unit test for that file, its not failing. But maybe i've not understood correctly what this class does.

the adapted test: (that passes)
https://gist.github.com/crooy/d3f463e7e2bc6d042c95ea9a736e1d1a

**Comment by HarelM** [comment] 2022-03-16 18:45
As I said, I'm not sure this is the root cause of this, but when I searched `.id` in the code, this was suspicious. If you can write a test that fails this specific case (not a stack blitz), it would be a great starting point to try and debug where the id "gets lost" I guess.

**Comment by HarelM** [comment] 2022-04-07 06:54
Checkout the following PR: https://github.com/maplibre/maplibre-gl-js/pull/1165
I think the docs are saying that id can only be a number or a string that can be casted to a number, but there's something about promoteId which I'm not sure I understand but seemed relevant.
@nreese can you comment if this issue is basically "work as designed"?

**Comment by nreese** [comment] 2022-04-07 12:24
@HarelM 
> @nreese can you comment if this issue is basically "work as designed"?

Yes, I would consider feature-state lookup working as designed

@crooy
Even though feature-state lookup is working as designed, the design is not in step with GeoJSON specification and this causes confusion. I have recently ran directly into this problem while trying to use feature-state to create choropleth maps. Below is my use case and how I solved it with `source.promoteId` settings. Maybe we could add a new documentation example showing promoteId and link to this in feature-state docs as a way to alleviate confusion?

Use case:
Create choropleth map that shows world countries shaded by web log traffic. Update web log traffic metrics as users interact with query, filts, and time range (in [Kibana maps](https://www.elastic.co/guide/en/kibana/current/maps.html))
* World countries are added to map as `vector` source. World countries have a property [iso2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) which I would like to use as the feature-state lookup value. This is possible by setting `source.promoteId`. Below is how I add source to map. A few notes about promoteId, [Elasticsearch vector tile search API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-vector-tile-api.html) returns 3 layers, "hits", "aggs", "meta". Layers referencing `source` set `source-layer` to "hits" 
    ```
   map.addSource('worldCountries', {
      type: 'vector',
      tiles: ['myWorldCountriesVectorTileUrlWhichArePulledFromElasticsearch'],
      minzoom: 0,
      maxzoom: 24,
      promoteId: {
        hits: 'iso2'
      }
    });
    ```
* Web log metrics are gathered with Elasticsearch [terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html). This gives me a table with `ISO_3166-1_alpha-2` column and then columns for each metric. I update feature-state with the following call.
    ```
    map.setFeatureState(
    {
      source: 'worldCountries',
      sourceLayer: 'hits',
      id: 'CN' // CN is ISO_3166-1_alpha-2 value for Canada 
    },
    {
      count: 1234,
      avg_bytes: 10000,
      ...
    });
    ```
* Then I can style world countries paint properties via feature-state. 
    ```
      {
      "id": "fce8ca4e-da4c-44d0-8d96-245c46b15024_fill",
      "type": "fill",
      "source": "worldCountries",
      "source-layer": "hits",
      "minzoom": 0,
      "maxzoom": 24,
      "filter": [
        "all",
        [
          "any",
          [
            "==",
            [
              "geometry-type"
            ],
            "Polygon"
          ],
          [
            "==",
            [
              "geometry-type"
            ],
            "MultiPolygon"
          ]
        ]
      ],
      "layout": {
        "visibility": "visible"
      },
      "paint": {
        "fill-color": [
          "interpolate",
          [
            "linear"
          ],
          [
            "coalesce",
            [
              "case",
              [
                "==",
                [
                  "feature-state",
                  "count"
                ],
                null
              ],
              122,
              [
                "max",
                [
                  "min",
                  [
                    "to-number",
                    [
                      "feature-state",
                      "count"
                    ]
                  ],
                  123
                ],
                123
              ]
            ],
            122
          ],
          122,
          "rgba(0,0,0,0)",
          123,
          "#6092c0"
        ],
        "fill-opacity": 0.75
      }
    }
    ```

**Comment by HarelM** [comment] 2022-04-07 12:57
Closing this for now as works as designed.
Feel free to move this to discussions or open a different issue in the docs repository to provide an example for other to use.
Thanks!

**Closed by HarelM** 2022-04-07 12:57 UTC

**Comment by thom4parisot** [comment] 2023-09-05 08:57
Hello, I tried https://stackblitz.com/edit/typescript-kmywnn?file=index.ts and updated `maplibre-gl` to `v3.3.1` with the `Update all to latest` button.

The reported behaviour persists, whereas I understood UUID should be acceptable values.
Is that correct?

**Comment by HarelM** [comment] 2023-09-05 10:40
No, as written in this thread, feature id must be a number, you can use another property and the promoteId settings of the source.

**Comment by willtemperley** [comment] 2023-09-28 10:59
Just running into this myself as I'm using a string feature id, which is within the GeoJSON spec:

https://datatracker.ietf.org/doc/html/rfc7946#section-3.2

 If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number.

**Comment by willtemperley** [comment] 2023-09-28 13:14
So it turns out the vector tile spec only allows for integer feature ids, hence MapLibre has to follow this as it generates vector tiles from GeoJSON under the hood.

https://github.com/maplibre/maplibre-gl-js/discussions/3134
