### ISSUE TITLE
text-field does't get in a line while using Chinese or other none-latin word

### ISSUE THREAD

**Issue by 1042041156** [maplibre/maplibre-gl-js#1010] opened 2022-02-18 06:34 UTC
**maplibre-gl-js version**: 2.1.6

**browser**: chrome 98

### Steps to Trigger Behavior

 1. type none-latin in text-field

### Link to Demonstration

[demo](https://jsbin.com/roqokaq/edit?html,output)

### Expected Behavior
text in in line

### Actual Behavior
it show in many lines

**Comment by HarelM** [comment] 2022-02-18 06:36
Duplicate of #1002

**Closed by HarelM** 2022-02-18 06:36 UTC
