### ISSUE TITLE
Using setTerrain changes the camera zoom behavior

### ISSUE THREAD

**Issue by Oreilles** [maplibre/maplibre-gl-js#1812] opened 2022-11-04 22:48 UTC
**maplibre-gl-js version**: 2.4.0

**browser**: Firefox 106.0.2

### Steps to Trigger Behavior

 1. Add a terrain source, then call `map.setTerrain()`
 2. Zoom on any location

### Link to Demonstration

Follow instructions from maptiler (https://www.maptiler.com/news/2022/05/maplibre-2/) or mapbox (https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/).

### Expected Behavior

The map should zoom towards the location under the mouse cursor, like it does without 

### Actual Behavior

The map zooms towards its center, regardless of where the cursor is. Removing the terrain with `map.setTerrain(null)` revert to the expected behavior.

**Comment by acalcutt** [comment] 2022-11-05 01:59
I think this is a known issue https://github.com/maplibre/maplibre-gl-js/issues/1024#issuecomment-1062769705

In 3d mode, right now it zooms to the center of the map and not to where the cursor is.

**Comment by HarelM** [comment] 2022-11-05 05:01
Duplicate of #1024

**Closed by HarelM** 2022-11-05 05:01 UTC
Labels: bug, duplicate

**Comment by Oreilles** [comment] 2022-11-05 11:22
Apologies, this is indeed a duplicate.
