### ISSUE TITLE
Map -> setTerrain should accept undefined

### ISSUE THREAD

**Issue by CraigglesO** [maplibre/maplibre-gl-js#2992] opened 2023-08-16 21:45 UTC
**maplibre-gl-js version**: latest

**browser**: any

### Steps to Trigger Behavior

 1. Initiate terrain data: `map.setTerrain({ ... })`
 2. Kill the terrain layer data: `map.setTerrain()`

### Link to Demonstration

https://github.com/maplibre/maplibre-gl-js/blob/deb12763e80bc8890783f6345f7886518c53089f/src/ui/map.ts#L1965-L1971

### Expected Behavior

Should be allowed to submit no data

### Actual Behavior

Typescript will yell at you for `map.setTerrain()`

**Comment by HarelM** [comment] 2023-08-17 03:53
I'm not sure I fully agree.
setTerrain(null) is much more descriptive and was the initial intention behind this API call.

**Comment by HarelM** [comment] 2023-08-17 10:21
This is basically a duplicate of #1781

**Comment by CraigglesO** [comment] 2023-08-17 10:39
Sure, I can see that being useful. I updated the PR to reflect this.

**Closed** 2023-08-17 11:55 UTC
Labels: need more info
