### ISSUE TITLE
map.isSourceLoaded(...) may return true while a GeoJSON source is still loading

### ISSUE THREAD

**Issue by vanilla-lake** [maplibre/maplibre-gl-js#669] opened 2021-11-30 14:22 UTC
**1.15.2**:

### Steps to Trigger Behavior

After the `map.load` event has fired, call `GeoJSONSource.setData(...)` twice, the first time passing a URL to a small GeoJSON file and the second time passing a URL to a large GeoJSON file.

### Link to Demonstration

https://jsbin.com/colaxiboka/2/edit?html,output

### Expected Behavior
- `map.isSourceLoaded(...)` should return `false` until the file specified in the last `GeoJSONSource.setData(...)` call has finished loading
- No points from the first GeoJSON file should be shown after the second call to `GeoJSONSource.setData(...)`

### Actual Behavior
- `map.isSourceLoaded(...)` returns `true` between the times the files specified in the two `GeoJSONSource.setData(...)` calls finish loading
- Points from the first GeoJSON file are shown between the time of the second `GeoJSONSource.setData(...)` call and the time the second file finishes loading

**Comment by vanilla-lake** [comment] 2021-11-30 14:48
I think the problem lies in the `actor.send(...)` callback in `GeoJSONSource._updateWorkerData` at the following line: https://github.com/maplibre/maplibre-gl-js/blob/d5d4e1d2300afd61830da2f2a9a79ffb5f60b3ae/src/source/geojson_source.ts#L286

The `actor.send(...)` callback runs once for each `GeoJSONSource.setData(...)` call. Since the first file is small and should thus load quickly, the `actor.send(...)` callback for the first `GeoJSONSource.setData(...)` call is called quickly, setting the `GeoJSONSource._loaded` flag to `true` before the callback for the second call runs.

The problematic sequence is:
1. `GeoJSONSource.setData(".../smaller.geojson")` is called.
2. `GeoJSONSource.setData(".../larger.geojson")` is called.
3. The `actor.send(...)` callback for the `GeoJSONSource.setData(".../smaller.geojson")` call runs, setting `GeoJSONSource._loaded` to `true`. At this point, `map.isSourceLoaded("geojson")` returns `true`.
4. The `actor.send(...)` callback for the `GeoJSONSource.setData(".../larger.geojson")` call runs, setting `GeoJSONSource._loaded` to `true` one more time.

**Comment by HarelM** [comment] 2021-11-30 19:39
This is an interesting analysis, thanks for sharing!
So the problem is some kind of race condition on the _loaded variable, right?
I see in the code that there's a check for abandoned, maybe two calls to setData should somehow trigger the abandoned for the first request. IDK...
In any case I would suggest to try and create a test that fails due to this race condition and see that it passes after you implement a fix.

**Comment by vanilla-lake** [comment] 2021-11-30 22:03
No problem, and yes, it seems to be a race condition on `GeoJSONSource._loaded`. I'll try creating the test and see if I can work on a potential fix.

**Comment by vanilla-lake** [comment] 2021-12-01 17:00
Based on the following unit test, it looks like the pending call is always expected to run to completion; only calls that have not yet started loading are abandoned when a new call is made: https://github.com/maplibre/maplibre-gl-js/blob/b2c300a69d3deb7f36099898acde2b1a3977bd45/test/unit/source/geojson_worker_source.test.js#L225-L245

Based on that, should we show data from the previous pending call when it gets loaded while data from the latest one is still loading? In other words, should we show stale data from the previous `GeoJSONSource.setData(...)` call that will soon be replaced by that of the latest one?

**Comment by HarelM** [comment] 2021-12-01 18:46
I believe we should present data from previous call to setData until a new data is ready, this is at least what I would expect.

**Comment by vanilla-lake** [comment] 2021-12-01 20:06
Sounds good. Thanks!

**Comment by HarelM** [comment] 2021-12-02 17:41
Fixed by #684

**Closed by HarelM** 2021-12-02 17:41 UTC

**Comment by vanilla-lake** [comment] 2021-12-06 20:08
re: https://github.com/maplibre/maplibre-gl-js/issues/669#issuecomment-983953402, do you think it could be worth adding a configuration option to GeoJSON sources that prevents stale data from being shown?

Our use case is that we call `GeoJSONSource.setData(...)` with a URL generated from a user query. If the user issues a query while the results from a previous one are loading, we don't want the results from the first query to show up while the results from the second are loading.

**Comment by HarelM** [comment] 2021-12-06 20:29
Personally, I would like to avoid complicating geojson with this kind of options... I'm not even sure where would one place such configuration option...
Can't you simply `setData` to empty array while waiting for the second request to load?

**Comment by vanilla-lake** [comment] 2021-12-06 20:42
We tried doing the following:
```javascript
// First query
GeoJSONSource.setData(url1);
// Second query (url1 is still loading)
GeoJSONSource.setData({type: "FeatureCollection", features: []});
GeoJSONSource.setData(url2);
```
Unfortunately, the `GeoJSONSource.setData({type: "FeatureCollection", features: []})` call gets abandoned when `GeoJSONSource.setData(url2)` is executed because of the following code: https://github.com/maplibre/maplibre-gl-js/blob/ddc348fe5892db8ec4884c2da37d4c3fe15f3c5d/src/source/geojson_worker_source.ts#L132-L135

**Comment by HarelM** [comment] 2021-12-06 21:02
What about removing and re-adding the source in order to abandon the current call and remove the data?

**Comment by vanilla-lake** [comment] 2021-12-06 21:10
I'd need to try it... My concern with that solution however is that, unless I'm wrong, all layers that use the source will need to be removed and re-added. While it's certainly possible to do that, it seems a bit cumbersome.
