### ISSUE TITLE
Remove vertex via delete key

### ISSUE THREAD

**Issue by h1ago** [maplibre/maplibre-gl-js#1829] opened 2022-11-08 20:51 UTC
Would it be possible in the next versions to come back with the functionality of removing a vertex through the keyboard delete button?

In this example from the [mapbox documentation](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/) it is possible to use the delete button on the keyboard to remove the vertex, in this example from the [maplibre documentation](https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/) it is not possible.

The maplibre version 1.14.0 has this functionality, however from version 1.15.0 onwards it no longer has this functionality.

As an alternative, I'm using a listener for the Delete key and running draw.trash(), but it would be ideal if it already had the option natively.

**Comment by HarelM** [comment] 2022-11-09 05:27
I don't think the problem is here but in the draw plugin. I'm also not sure how well it will support newer versions of maplibre...

**Comment by h1ago** [comment] 2022-11-15 17:18
I looked at the maplibre and mapbox-gl-draw changelogs, but I wasn't able to identify which change could have generated this behavior. I tested all versions of mapbox-gl-draw with all versions of maplibre and only one is compatible, so I associated it with some change in maplibre. Thank you @HarelM

**Comment by HarelM** [comment] 2022-12-01 06:56
I think there are some alternatives to mapbox-draw from what I saw in the slack channel.
I also believe the issue is not with this library.
There's nothing against sending a PR if this helps with needed external API, but as for tracking this here, I'm closing this issue.
Feel free to continue posting here if needed.

**Closed by HarelM** 2022-12-01 06:56 UTC
