### ISSUE TITLE
mapbox-gl-draw plugin no longer renders buttons correctly

### ISSUE THREAD

**Issue by chriswthomson** [maplibre/maplibre-gl-js#2734] opened 2023-06-27 13:52 UTC
**maplibre-gl-js version**: 3.0.0+

**browser**: all

### Link to Demonstration

https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw

### Expected Behavior

Buttons render as per 2.4.0

### Actual Behavior

They don't render correctly. I tried adding the CSS from version 2.4.0 which got it some of the way there but not completely.

I assume this is related to https://github.com/maplibre/maplibre-gl-js/pull/1575

It would be good to have a way to use this plugin with v3. Alternatively I'll persist with 2.4.0, but the example(s) should probably be removed.

**Comment by HarelM** [comment] 2023-06-27 14:27
Yes, and it's also a duplicate of #2601 and a bunch of others...

**Closed by HarelM** 2023-06-27 14:27 UTC

**Comment by chriswthomson** [comment] 2023-06-27 14:50
Ah apologies, I'd only searched open tickets assuming it was still an ongoing issue.

**Comment by HarelM** [comment] 2023-06-27 14:54
It is, but not in this repo 😀
