### ISSUE TITLE
globe projection render errors after v5.0.0-pre7 with pmtiles

### ISSUE THREAD

**Issue by resiliencetheatre** [maplibre/maplibre-gl-js#5242] opened 2024-12-19 00:32 UTC
**maplibre-gl-js version**:

* All pre-releases after 5.0.0-pre.7

**browser**: Firefox 128.5.0esr (debian 12)

### Steps to Trigger Behavior

 1. Replace maplibre-gl-js 5.0.0-pre.7 with more recent pre version (tested up to pre.10)
 2. Open map using pmtiles with globe projection and it renders bad

### Link to Demonstration

v5.0.0-pre.10

![Image](https://github.com/user-attachments/assets/8eaebe01-6cca-42c3-9fd2-9e73face1dbb)

### Expected Behavior

v5.0.0-pre.7

![Image](https://github.com/user-attachments/assets/9258e359-453a-4798-bcea-154f8eb62ac6)

**Comment by HarelM** [comment] 2024-12-19 06:38
Please provide a proper way to reproduce this issue, screenshots are not enough. 
Can you also please see if you can find the offending PR that broke this?

**Comment by resiliencetheatre** [comment] 2024-12-20 06:45
Way to reproduce: 

1. Get example:
https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html

2. Change line 39 to:
url: "pmtiles://https://data.source.coop/protomaps/openstreetmap/v4.pmtiles",

3. Extract pre7 and pre10 as dist7 and dist10 directories under web server

4. Modify lines 5 and 6 to load either pre.7 or pre.10 versions of maplibre-gl-js

Observe that pre.10 leaves tiles unloaded, while pre.7 loads them perfectly.

**Comment by HarelM** [comment] 2024-12-20 09:02
Can you create a JSBin or something similar? It's hard to understand the steps to reproduce this way.
I would also be surprised if this is only relevant to PMTiles so I would encourage you to try and create a reproduction that doesn't require PMTiles.
CC: @kubapelc

**Comment by resiliencetheatre** [comment] 2024-12-20 10:38
Thanks. I'll try better. That 120 GB pmtiles (world) is tough act to deliver as part of demo - but I'll see if I can make it happen. My instance is 100% localhost running on RPi4 and taking it out from there is bit painful and my frontend skills with tooling are bad. But let me see.

**Comment by resiliencetheatre** [comment] 2024-12-20 23:53
I was able to get [this example](https://github.com/maplibre/maplibre-gl-js/issues/5242#issuecomment-2556389660) to show similar thing (even without globe), so it might be fastest way to test it.

**Comment by HarelM** [comment] 2024-12-22 09:52
Can you please provide a jsbin with the issue? I'm having a hard time understanding how to reproduce this, and what is the minimal reprodction, and if it's related to globe or not, if it's related to pmtiles or not.
There's too many noise and too much comments.
A jsbin with a minimal reproduction can go a long way here...

**Comment by CommanderStorm** [comment] 2024-12-22 21:16
I think [this](https://jsbin.com/gogokecomi/1/edit?output) is a pretty minimal reproduction.

I can reproduce this without the globe mode on large zoom levels, this is only realted to pmtiles.

**Comment by HarelM** [comment] 2024-12-23 14:12
Thanks!
I'm able to see an issue, not sure if it's the same as the problem in the globe though. It looks as follows (missing tiles like checkers board):
![Image](https://github.com/user-attachments/assets/31328cb2-cd87-4cc5-a4c8-89617ad1bc5f)

It looks like the issue starts in version pre.9 and does not happen in version pre.8.
Looking at the changelog, the most probably offending PR is:
- #5101

But further investigation is still needed.
CC: @NathanMOlson can you take a look at this as well?

**Comment by HarelM** [comment] 2024-12-23 16:37
I stand corrected, I believe the offending commit is the following:
- #5166

@0xFA11 can you please take a look at what might have cause this issue? The PR itself seems innocent, but I think I narrowed it down to this PR...

**Comment by HarelM** [comment] 2024-12-23 16:50
Ignore me... I'm struggling to find the offending commit for some reason..

**Comment by HarelM** [comment] 2024-12-23 17:04
This is due to the breaking change in geometry-type related to version 5.
Closing this as this is working as expected.
You can change the filter to `filter: ["==","$type","Polygon"],` or `filter: ["in", ["geometry-type"], ["literal", ["Polygon", "MultiPolygon"]]],`

**Closed by HarelM** 2024-12-23 17:04 UTC
Labels: bug, globe, showstopper

**Comment by 0xFA11** [comment] 2024-12-24 15:13
I was happy to jump in but looks like you found the main offender @HarelM — please feel free to loop me in for WebGL/WGSL related compatibility issues though.

**Comment by resiliencetheatre** [comment] 2025-01-04 04:56
Any idea when this fix could be included to release?

**Comment by resiliencetheatre** [comment] 2025-01-04 05:06
> This is due to the breaking change in geometry-type related to version 5. Closing this as this is working as expected. You can change the filter to `filter: ["==","$type","Polygon"],` or `filter: ["in", ["geometry-type"], ["literal", ["Polygon", "MultiPolygon"]]],`

How and where this change should be applied?

**Comment by HarelM** [comment] 2025-01-04 07:07
This change should be applied to expressions that have geometry-type in the style and relay on the "bug" that was fixed as part of version 5.

**Comment by bdon** [comment] 2025-01-04 13:34
See https://github.com/protomaps/basemaps/pull/341
