### ISSUE TITLE
Map crashes after turning off terrain

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1185] opened 2022-04-15 06:01 UTC
**maplibre-gl-js version**: terrain3d branch d8aa186a20650db2706b6ff2e88682d918a1b2e4

**browser**:  Google Chrome  99.0.4844.84 on linux

### Steps to Trigger Behavior

 1. `npm run start-debug`
 2. Go to http://0.0.0.0:9966/debug/terrain.html
 3. Click terrain button
 4. Pan map which is now in 2D mode
 5. After pan, map crashes with this error message in the console `Uncaught TypeError: Cannot read properties of null (reading 'getElevation')`

### Expected Behavior

Switch between 2D and 3D with the terrain control button without seeing crashes.

### Actual Behavior

Go from 3D to 2D with terrain control button followed by pan leads to crash.

**Comment by wipfli** [comment] 2022-04-15 06:01
This is the new demo page that I used and propose in #1184 :+1: 
```html
<!DOCTYPE html>
<html>
<head>
   <title>MapLibre GL JS debug page for terrian</title>
   <meta charset='utf-8'>
   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
   <link rel='stylesheet' href='../dist/maplibre-gl.css' />
   <style>
       body { margin: 0; padding: 0; }
       html, body, #map { height: 100%; }
   </style>
</head>

<body>
<div id='map'></div>

<script src='../dist/maplibre-gl-dev.js'></script>
<script>

var map = window.map = new maplibregl.Map({
    container: 'map',
    zoom: 12,
    center: [11.39085, 47.27574],
    pitch: 52,
    hash: true,
    style: {
        version: 8,
        sources: {
            osm: {
                type: 'raster',
                tiles: ['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
                tileSize: 256,
                attribution: '&copy; OpenStreetMap Contributors',
                maxzoom: 19
            },
            terrain: {
                type: 'raster-dem',
                url: 'https://api.maptiler.com/tiles/terrain-rgb/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL',
                tileSize: 256
            },
        },
        layers: [
            {
                id: 'osm',
                type: 'raster',
                source: 'osm'
            },
            {
                id: 'hills',
                type: 'hillshade',
                source: 'terrain',
                layout: {'visibility': 'visible'},
                paint: {'hillshade-exaggeration': 0.33}
            }
        ],
        terrain: {
            source: 'terrain',
            exaggeration: 1
        }
    },
    maxZoom: 18,
    maxPitch: 85
});

map.addControl(new maplibregl.NavigationControl({
    visualizePitch: true,
    showZoom: true,
    showCompass: true
}));

map.addControl(
    new maplibregl.TerrainControl({
        source: 'terrain',
        exaggeration: 1
    })
);
</script>
</body>
</html>
```

**Comment by prozessor13** [comment] 2022-04-16 07:20
Hello, should be fixed with last commit.

**Comment by HarelM** [comment] 2022-04-16 12:17
I can't reproduce with latest code, clsoing.

**Closed by HarelM** 2022-04-16 12:17 UTC
Labels: Terrain 3D, Terrain 3D Blocker
