### ISSUE TITLE
Incorrect dom event coordinates for scaled container

### ISSUE THREAD

**Issue by huanglii** [maplibre/maplibre-gl-js#3506] opened 2023-12-21 11:41 UTC
**maplibre-gl-js version**: 3.6.2

**browser**:

### Steps to Trigger Behavior

 1. Set the parent container with 'scale':  `<div style="height: 100%; transform: scale(0.8);"><div id="map"></div></div>`
 2. Hover the feature
 3.

### Link to Demonstration

https://jsbin.com/taqovog/edit?html,output

### Expected Behavior
`scale(1)`
![PixPin_2023-12-21_21-28-38](https://github.com/maplibre/maplibre-gl-js/assets/20068340/0ac0da27-be90-48d0-a0a4-412ad234c163)

### Actual Behavior
`scale(0.8)`
![PixPin_2023-12-21_21-27-12](https://github.com/maplibre/maplibre-gl-js/assets/20068340/8b7db9d1-835e-4285-a39b-e503c6f128a8)

**Comment by HarelM** [comment] 2023-12-21 11:59
Please elaborate on the issue.
From the above description and title, it is impossible to understand what the issue is.

**Comment by huanglii** [comment] 2023-12-21 13:30
Related: https://github.com/maplibre/maplibre-gl-js/pull/218

**Comment by huanglii** [comment] 2023-12-21 13:32
I think it's the same problem: https://github.com/mapbox/mapbox-gl-js/pull/10096

**Comment by HarelM** [comment] 2023-12-21 14:12
Have you tried with the latest version with the following PR:
https://github.com/maplibre/maplibre-gl-js/pull/3437

**Comment by huanglii** [comment] 2023-12-21 14:52
> Have you tried with the latest version with the following PR:
> 
> * [Correct mouse position even when scaling the map using CSS #3437](https://github.com/maplibre/maplibre-gl-js/pull/3437)

It solves the problem. Thanks

**Comment by HarelM** [comment] 2023-12-21 14:54
Fixed by #3437

**Closed by HarelM** 2023-12-21 14:54 UTC
Labels: need more info
