### ISSUE TITLE
deck.gl mapbox Interleaved layer coved by 3d building layer

### ISSUE THREAD

**Issue by longxiutmm** [maplibre/maplibre-gl-js#1369] opened 2022-07-11 02:21 UTC
I use Deck.gl MapboxLayer 、ArcLayer with maplibre 2.1.9, the 3d building layer always cover the arcLayer. This was working as expected in maplibre-gl up till v1.15.3。

![177907379-c976b83b-381d-451e-a01a-66832accbbfb](https://user-images.githubusercontent.com/19338062/178176373-7fb87ce7-861f-4d73-b631-8fcac263c815.png)

blow is my code.

```html
<html>
<head>
    <title>Interleaving deck.gl with Mapbox Layers</title>
    <script src="https://unpkg.com/deck.gl@^8.8.0/dist.min.js"></script>

    <script src='https://unpkg.com/maplibre-gl@2.1.9/dist/maplibre-gl.js'></script>
    <link href='https://unpkg.com/maplibre-gl@2.1.9/dist/maplibre-gl.css' rel='stylesheet' />

</head>

<body style="margin:0">


</body>

<script type="text/javascript">

    const {MapboxLayer, ScatterplotLayer, ArcLayer} = deck;

    var map = new maplibregl.Map({
        container: document.body,
        style: 'https://api.maptiler.com/maps/streets/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL', // stylesheet location
        center: [-122.4, 37.79],
        zoom: 15,
        pitch: 60
    });


    map.on('load', () => {
        const firstLabelLayerId = map.getStyle().layers.find(layer => layer.type === 'symbol').id;


        map.setPaintProperty('building-3d','fill-extrusion-opacity',0.8);


        map.addLayer(new MapboxLayer({
            id: 'deckgl-circle',
            type: ScatterplotLayer,
            data: [
                {position: [-122.402, 37.79], color: [255, 0, 0], radius: 1000}
            ],
            getPosition: d => d.position,
            getFillColor: d => d.color,
            getRadius: d => d.radius,
            opacity: 0.3
        }), firstLabelLayerId);

        map.addLayer(new MapboxLayer({
            id: 'deckgl-arc',
            type: ArcLayer,
            data: [
                {source: [-122.3998664, 37.7883697], target: [ -122.41460563510304,  37.79512692863844]}
            ],
            getSourcePosition: d => d.source,
            getTargetPosition: d => d.target,
            getSourceColor: [255, 208, 0],
            getTargetColor: [0, 128, 255],
            getWidth: 20
        }))
    });

</script>
</html>
```

**Comment by HarelM** [comment] 2022-07-11 19:05
I don't know what `MapboxLayer` is, but it sound like something related to mapbox.
Maplibre and mapbox are diverging since they are maintained by different organizations with different agendas.
You could check in the changelog/commits history what might have caused this break and see how you can overcome it I guess, but we are not maintaining this plugin so I think this issue should be opened there and not here...

**Comment by birkskyum** [comment] 2022-08-28 21:38
I believe this is a duplicate of #1426, which is fixed from our side now by exposing the version number for maplibre, which deck.gl uses to handle this.

**Closed by birkskyum** 2022-08-28 21:38 UTC
Labels: bug, PR is more than welcomed
