### ISSUE TITLE
Implement `cooperativeGestures` similar to Mapbox

### ISSUE THREAD

**Issue by choffa** [maplibre/maplibre-gl-js#661] opened 2021-11-24 14:14 UTC
## Motivation

Both Google and Mapbox has standardised around having an option to require the using a meta key to scroll on desktop (ctrl or ⌘ depending on platform) or using two fingers to pan on mobile/touch. This is to prevent unwanted scroll-capture. A similar feature should exist in Maplibre as well. While it has been suggested in other issues to do this manually, I think it is easier, more consistent, and therefore more user friendly to have this as a feature of the library itself.

## Design Alternatives

My suggestion would be to use the same API design as Mapbox which uses a [cooperativeGestures option](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters). The overlay could be similar as well, with a semi-transparent layer covering the entire map and displaying instructions on how to interact with the map. See for example mapbox/mapbox-gl-js#2618 and mapbox/mapbox-gl-js#6884

**Comment by HarelM** [comment] 2021-11-24 14:40
I think this is a duplicate of #234.
The comments I made there seems relevant to this issue I believe. You can check with the author there why they chose to close the original issue.
Please close this one of this is a duplicate, and key me know if you would like me to reopen the other one.

**Comment by choffa** [comment] 2021-11-24 14:51
Yes it is the same basic idea as #234 and it is the issue that i reference where the suggestion to do this manually was made. If you feel that it is more appropriate to re-open that issue, go right ahead, and we can discuss further there :)

**Comment by HarelM** [comment] 2021-11-24 14:54
Closing in favir if #234

**Closed by HarelM** 2021-11-24 14:54 UTC
