### ISSUE TITLE
Duplicated render of buildings' roof in 3D terrain

### ISSUE THREAD

**Issue by AlvaroRuC** [maplibre/maplibre-gl-js#3786] opened 2024-03-04 21:30 UTC
**maplibre-gl-js version**: 4.1.0

**browser**: Firefox and Chrome

### Steps to Trigger Behavior
Observe buildings with different levels of zoom and pitch. The problem is visible especially in buildings that are located on steep slopes.

### Link to Demonstration

https://madridxix.es/IDE-2/Test.html

### Expected Behavior

Correct render of 3d buildings in terrain.

![Screenshot 2024-03-03 at 11-14-00 Madrid XIX 3D](https://github.com/maplibre/maplibre-gl-js/assets/149305775/9ca719da-cac0-4477-91db-dc3a036884ea)

### Actual Behavior

The render of the roof of the buildings is duplicated and moved vertically. Especially when the buildings are far from the point of view.

![Screenshot 2024-03-03 at 11-13-53 Madrid XIX 3D](https://github.com/maplibre/maplibre-gl-js/assets/149305775/876a34d9-9a72-48f1-af0d-c7e0aa95c7ae)

**Comment by HarelM** [comment] 2024-03-06 11:11
@AlvaroRuC do you think this is the same problem as described here:
https://github.com/maplibre/maplibre-gl-js/issues/2560
If not, I would recommend creating a more simplified version of this issue.
Understanding what went wrong here can be very complicated due to the complexity of the scene.

**Comment by AlvaroRuC** [comment] 2024-03-07 20:52
Thank you @HarelM, for your answer. I think you are right and it is the same issue.

**Comment by HarelM** [comment] 2024-03-07 21:17
I'll close this as duplicate of #2560.
If you create a minimal reproduction that has different characteristics, feel free to comment here and I'll reopen.

**Closed by HarelM** 2024-03-07 21:17 UTC
Labels: bug, need more info, Terrain 3D
