### ISSUE TITLE
add labels from geojson issues

### ISSUE THREAD

**Issue by gisfinder** [maplibre/maplibre-gl-js#2985] opened 2023-08-14 15:14 UTC
**Maplibre version**: 3.30
Issue description:  If the map is initiated without  maptiler style(such as from ESRI),  the label will not display.
The codes as the example : [https://maplibre.org/maplibre-gl-js/docs/examples/variable-label-placement/](https://maplibre.org/maplibre-gl-js/docs/examples/variable-label-placement/ )

The codepen link  can reproduce this issue : [https://codepen.io/gisfinder/pen/YzRmeOe?editors=1011](https://codepen.io/gisfinder/pen/YzRmeOe?editors=1011)

**maplibre-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by HarelM** [comment] 2023-08-14 15:38
According to the console log in the above codepen link, the problem is that the style is broken and thus nothing gets rendered...
Please try using OSM raster tiles instead of ESRI...

**Comment by gisfinder** [comment] 2023-08-15 13:39
I updated the[ code pen](https://codepen.io/gisfinder/pen/YzRmeOe?editors=1011) by using OSM satellite and it works.   The ESRI's background service is our best choice on the point of speed,content  and pricing.  I tried another exapmle for display clustered numbers. With ESRI background the number as labels are displayed. The code pen is as follow: [https://codepen.io/gisfinder/pen/WNYVVwj?editors=1011](https://codepen.io/gisfinder/pen/WNYVVwj?editors=1011) . In the console it has the same exception. I could not understand the added label depends on the map's loaded style? I have the ArcGIS style file hosted locally.  What modification done on the style file to solve it or    any idea to  bypass it?

**Comment by gisfinder** [comment] 2023-08-16 01:44
I updated the[ code pen](https://codepen.io/gisfinder/pen/YzRmeOe?editors=1011) by using OSM satellite and it works.   The ESRI's background service is our best choices on the point of speed and pricing. I have the ArcGIS style file hosted locally.  What modification done on the style file to solve it or    any idea to  bypass it?

**Comment by HarelM** [comment] 2023-08-16 05:30
When there's a problem in the style, as stated above, the map won't show.
I would try and reduce the style to something that works and incrementally add things until it fails.
The original error in the console might have indicated that the vector tiles are invalid - i.e. the source, I would start from there as you said that switching to osm solved this.
I don't see a problem with maplibre though, so I'm closing this issue.

**Closed by HarelM** 2023-08-16 05:30 UTC
Labels: need more info

**Comment by gisfinder** [comment] 2023-08-16 15:00
Only load one layer of ESRI , and tried to write the style as what maptiler done, the label still not appear.  The style file is attached and it can be hosted locally. 
 The map initialized code as this :
     `const map = new maplibregl.Map({
        container: "map",  
     style: '../style/styleNone.json',
          zoom: 12,  
      center: [87.582712, 43.819312]  
    });` 

The style file is attached.
[styleNone.zip](https://github.com/maplibre/maplibre-gl-js/files/12360713/styleNone.zip)

**Comment by gisfinder** [comment] 2023-08-17 15:48
Hello @HarelM , thre is a solution on it. Copied  one layer of ESRI's label style of "layout" and "paint" and set it to the added geojson objects. Then they are  displayed.

**Comment by HarelM** [comment] 2023-08-17 17:47
Good question, I've been using spritezero to generate those:
https://github.com/elastic/spritezero
Worth adding this to the docs I guess if its not there.

**Comment by gisfinder** [comment] 2023-08-18 02:57
For the above label not displayed issue, I guess it is caused by "text-font" not configured.  In the library API  if the label font configured will use a default font which is included in maptiler. While the default font not in ArcGIS fonts.   For  the sprite I will try it. Thank you so much.
