### ISSUE TITLE
Custom Markers are broken with v3.2.0

### ISSUE THREAD

**Issue by jwoodwardtfx** [maplibre/maplibre-gl-js#2864] opened 2023-07-12 13:51 UTC
Go to the custom marker example page at https://maplibre.org/maplibre-gl-js/docs/examples/custom-marker-icons/

The custom markers used to be images of kittens (in v3.1.0), now it's just the default blue tear drop (in v3.2.0).

I've seen the same regression in my own projects using custom markers.

**Comment by HarelM** [comment] 2023-07-12 13:57
Duplicate of #2855

**Closed by HarelM** 2023-07-12 13:57 UTC
