### ISSUE TITLE
map crashes when panning through mountains in 3D terrain (even on maplibre docs itself)

### ISSUE THREAD

**Issue by Fabioni** [maplibre/maplibre-gl-js#4235] opened 2024-06-06 00:11 UTC
**maplibre-gl-js version**: 4.3.2

**browser**: Chrome

### Link to Demonstration

Your own documentation: https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/

### Behavior

Zoon in a bit and than pan forwards so the camera goes through the mountains in Innsbruck. This crashed the map meaning the map turn white and the console repeatedly outputs this error. Nothing works anymore and only reloading the website helps.

```
lng_lat.ts:63 Uncaught 
Error: Invalid LngLat object: (NaN, NaN)
    at new Sc (lng_lat.ts:63:19)
    at Cc.toLngLat (mercator_coordinate.ts:126:16)
    at pa.coordinateLocation (transform.ts:584:31)
    at pa.pointLocation (transform.ts:565:21)
    at t.Map.unproject (map.ts:1173:31)
    at new Ea (events.ts:527:28)
    at Da.mousemove (map_event.ts:122:24)
    at HTMLDivElement.handleEvent (handler_manager.ts:391:51)
```

**Comment by HarelM** [comment] 2024-06-06 05:28
I believe once #1542 is solved, this issue would not be relevant, right?

-  #1542

**Comment by chrneumann** [comment] 2024-06-06 14:02
Guess so, at least I can't reproduce this bug with my local fix of #1542. There might be some edge cases though.

**Comment by kudlav** [comment] 2024-06-27 11:19
I can even zoom in to NaN when scrolling. Zooming in can cause zooming into the terrain when using a map with tilted terrain.

```
Uncaught Error: failed to invert matrix
Uncaught Error: Invalid LngLat object: (NaN, NaN)
```

**Comment by AEiosApp** [comment] 2024-08-09 21:50
Got same issue on Android browser (same code on Chrome in Macbook works fine).

Steps to reproduce:
- zoom the map less than your hillshade tiles maxzoom (e.g. 12)
- turn on terrain
- if I move through the map on this zoom level - everything is fine
- if I zoom in (e.g. 14) - map crashes with `Invalid LngLat object` error

**Comment by HarelM** [comment] 2024-08-11 10:07
4.5.2 Should be out shortly, please test to see if this issue is still relevant after the relevant fix was introduced.

**Comment by AEiosApp** [comment] 2024-08-12 15:29
@HarelM Just tested with 4.5.2 - **issue has gone!**

Great work, thanks!

**Comment by HarelM** [comment] 2024-08-12 19:39
Fixed by #4300

**Closed by HarelM** 2024-08-12 19:39 UTC
Labels: bug, PR is more than welcomed, need more info, Terrain 3D

**Comment by kudlav** [comment] 2024-08-12 20:06
I can still zoom into hills on https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/ page:

`Uncaught Error: Invalid LngLat object: (NaN, NaN)`

**Comment by HarelM** [comment] 2024-08-13 04:52
@chrneumann can you check this report?

**Comment by chrneumann** [comment] 2024-08-13 08:57
From the comments it seems that the calculations there are not supposed to be correct? Maybe at least some additional checks should prevent that the map crashes, e.g. for the `NaN` case. So if the calculated zoom is `NaN`, don't set it / give a warning instead until this is fixed.

**Comment by chrneumann** [comment] 2024-08-13 08:59
It's easy to see the wrong calculation if you "Pause on exceptions" in browser debugger.

**Comment by HarelM** [comment] 2024-08-13 09:02
I've reopened the following bug as I can still get to a state where the camera is inside the terrain using accepted user behavior (pan, zoom, didn't try rotate but this should be checked too).
Let's see if fixing the bug below does not solve this issue and I'll reopen this one, or open a different bug.
- https://github.com/maplibre/maplibre-gl-js/issues/1542

Let's keep the conversation in the above linked bug as I think they are related.
