### ISSUE TITLE
`mismatched image size` occurs in rendering multi-bytes fonts

### ISSUE THREAD

**Issue by Kanahiro** [maplibre/maplibre-gl-js#995] opened 2022-02-12 21:02 UTC
**maplibre-gl-js version**: v2.0.0 or higher

**browser**: tested on Chrome 97.0.4692.99

### Steps to Trigger Behavior

 1. load MapLibre via CDN
 2. set style including symbol layer which has multi-bytes text 
 3. no texts are shown and many errors logged in console (and style may be broken)

#### v2.1.1 (newest, broken)

https://jsbin.com/dojicuciha/edit?html,output (osm.jp vectortile)

https://jsbin.com/racafokigi/edit?html,output (MapTiler Basic)

You can see this issue by zooming into Japan or east Asia.

#### v1.15.2

https://jsbin.com/duzinusoda/edit?html,output (osm.jp vectortile)

https://jsbin.com/wemifodaho/edit?html,output (MapTiler Basic)

same code and style works in v1.15.2.

**Comment by wipfli** [comment] 2022-02-12 21:06
#718

**Comment by HarelM** [comment] 2022-02-12 21:07
Seems like a duplicate of #718 closing. In case this is not fixed in latest version (whenever we'll be able to properly publish it please reopen :-))

**Closed by HarelM** 2022-02-12 21:07 UTC
