### ISSUE TITLE
ReferenceError: y is not defined

### ISSUE THREAD

**Issue by tengl** [maplibre/maplibre-gl-js#2222] opened 2023-02-23 10:30 UTC
We get `ReferenceError: y is not defined` in our React app. We are using `react-script` (Create React App). The error only appears in the build version (`npm run build`), not debug (`npm run start`). 

**maplibre-gl-js version**: 2.4.0

**browser**: Chrome

### Steps to Trigger Behavior

1. Clone the repo and read README.md: https://github.com/tengl/maplibre-y-not-defined

or

 1. Create a react app according to https://create-react-app.dev/docs/getting-started
 2. Add a maplibre component. 
 3. Build the project
 4. Serve the `build` folder. 

### Link to Demonstration
https://github.com/tengl/maplibre-y-not-defined

### Expected Behavior
Not to get the error and working map. We don't get it in maplibre-gl 1.15.3. 

### Actual Behavior
Getting the error and map doesn't work.

**Comment by HarelM** [comment] 2023-02-23 10:34
Duplicate of https://github.com/maplibre/maplibre-gl-js/discussions/372

**Closed by HarelM** 2023-02-23 10:34 UTC

**Comment by tengl** [comment] 2023-02-23 10:58
For others, here's what works now. This might be a pointer on what to look at if there is a difference between production and development. 

```json
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not ie 11",
      "not chrome < 51",
      "not safari < 10",
      "not android < 51"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by ailuoamang** [comment] 2023-11-01 05:43
that's useful
