### ISSUE TITLE
When I load terrain and 3D model offset visual angle height jump

### ISSUE THREAD

**Issue by bk201lucifer** [maplibre/maplibre-gl-js#2240] opened 2023-03-02 09:35 UTC
Here is my code

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>three.js</title>
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <script src="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.js"></script>
    <link
      href="https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css"
      rel="stylesheet"
    />
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <script src="https://unpkg.com/three@0.147.0/build/three.min.js"></script>
    <script src="https://unpkg.com/three@0.147.0/examples/js/loaders/GLTFLoader.js"></script>
    <div id="map"></div>
    <script>
      var map = (window.map = new maplibregl.Map({
        container: "map",
        zoom: 16,
        pitch: 52,
        center: [11.443634033203125, 47.3616181216039],
        style: {
          version: 8,
          sources: {
            osm: {
              type: "raster",
              tiles: ["https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"],
              tileSize: 256,
              attribution: "&copy; OpenStreetMap Contributors",
              maxzoom: 19,
            },
            terrainSource: {
              type: "raster-dem",
              url: "https://demotiles.maplibre.org/terrain-tiles/tiles.json",
              tileSize: 256,
            },
            hillshadeSource: {
              type: "raster-dem",
              url: "https://demotiles.maplibre.org/terrain-tiles/tiles.json",
              tileSize: 256,
            },
          },
          layers: [
            {
              id: "osm",
              type: "raster",
              source: "osm",
            },
            {
              id: "hills",
              type: "hillshade",
              source: "hillshadeSource",
              layout: { visibility: "visible" },
              paint: { "hillshade-shadow-color": "#473B24" },
            },
          ],
          terrain: {
            source: "terrainSource",
            exaggeration: 1,
          },
        },
        antialias: true,
      }));

      map.addControl(
        new maplibregl.NavigationControl({
          visualizePitch: true,
          showZoom: true,
          showCompass: true,
        })
      );

      map.addControl(
        new maplibregl.TerrainControl({
          source: "terrainSource",
          exaggeration: 1,
        })
      );

      map.on("load", (e) => {
        let geojson = {
          type: "FeatureCollection",
          features: [
            {
              type: "Feature",
              properties: {},
              geometry: {
                coordinates: [
                  [
                    [11.990203857421875, 47.05234716672979],
                    [11.00555419921875, 47.05234716672979],
                    [11.006927490234375, 47.735629051492964],
                    [11.970977783203125, 47.73470543306706],
                    [11.990203857421875, 47.05234716672979],
                  ],
                ],
                type: "Polygon",
              },
            },
          ],
        };
        map.addSource("hexGrid", {
          type: "geojson",
          data: geojson,
        });
        map.addLayer({
          id: "ploygon",
          type: "fill",
          source: "hexGrid",
          layout: {},
          paint: {
            "fill-color": "red",
            "fill-opacity": 0.6,
          },
        });
      });
      var modelOrigin = [11.443634033203125, 47.3616181216039];
      // var modelOrigin = [148.9819, -35.3981];
      var modelAltitude = 200;
      var modelRotate = [Math.PI / 2, 0, 0];

      var modelAsMercatorCoordinate = maplibregl.MercatorCoordinate.fromLngLat(
        modelOrigin,
        modelAltitude
      );

  
      var modelTransform = {
        translateX: modelAsMercatorCoordinate.x,
        translateY: modelAsMercatorCoordinate.y,
        translateZ: modelAsMercatorCoordinate.z,
        rotateX: modelRotate[0],
        rotateY: modelRotate[1],
        rotateZ: modelRotate[2],
        
        scale: modelAsMercatorCoordinate.meterInMercatorCoordinateUnits(),
      };

      var THREE = window.THREE;

      var customLayer = {
        id: "3d-model",
        type: "custom",
        renderingMode: "3d",
        onAdd: function (map, gl) {
          this.camera = new THREE.Camera();
          this.scene = new THREE.Scene();

      
          var directionalLight = new THREE.DirectionalLight(0xffffff);
          directionalLight.position.set(0, -70, 100).normalize();
          this.scene.add(directionalLight);

          var directionalLight2 = new THREE.DirectionalLight(0xffffff);
          directionalLight2.position.set(0, 70, 100).normalize();
          this.scene.add(directionalLight2);

        
          var loader = new THREE.GLTFLoader();
          loader.load(
            "https://maplibre.org/maplibre-gl-js-docs/assets/34M_17/34M_17.gltf",
            function (gltf) {
              this.scene.add(gltf.scene);
            }.bind(this)
          );
          this.map = map;

          
          this.renderer = new THREE.WebGLRenderer({
            canvas: map.getCanvas(),
            context: gl,
            antialias: true,
            logarithmicDepthBuffer: true, 
          });

          this.renderer.autoClear = false;
        },
        render: function (gl, matrix) {
          var rotationX = new THREE.Matrix4().makeRotationAxis(
            new THREE.Vector3(1, 0, 0),
            modelTransform.rotateX
          );
          var rotationY = new THREE.Matrix4().makeRotationAxis(
            new THREE.Vector3(0, 1, 0),
            modelTransform.rotateY
          );
          var rotationZ = new THREE.Matrix4().makeRotationAxis(
            new THREE.Vector3(0, 0, 1),
            modelTransform.rotateZ
          );

          var m = new THREE.Matrix4().fromArray(matrix);
          var l = new THREE.Matrix4()
            .makeTranslation(
              modelTransform.translateX,
              modelTransform.translateY,
              modelTransform.translateZ
            )
            .scale(
              new THREE.Vector3(
                modelTransform.scale,
                -modelTransform.scale,
                modelTransform.scale
              )
            )
            .multiply(rotationX)
            .multiply(rotationY)
            .multiply(rotationZ);

          this.camera.projectionMatrix = m.multiply(l);
          this.renderer.resetState();
          this.renderer.render(this.scene, this.camera);
          this.map.triggerRepaint();
        },
      };

      map.on("style.load", function () {
        map.addLayer(customLayer);
      });

      
    </script>
  </body>
</html>

**Comment by HarelM** [comment] 2023-03-02 10:13
Is this the same as #1654 ?

**Comment by bk201lucifer** [comment] 2023-03-03 01:21
Yes, that's the problem

**Comment by bk201lucifer** [comment] 2023-03-03 01:23
Sorry I didn't see  1654

**Comment by HarelM** [comment] 2023-03-03 03:28
Duplicate of #1654

**Closed by HarelM** 2023-03-03 03:28 UTC
Labels: need more info
