### ISSUE TITLE
Map moves slightly in elevation when map.stop() is called and an animation was playing.

### ISSUE THREAD

**Issue by doubotis** [maplibre/maplibre-gl-js#2687] opened 2023-06-15 11:28 UTC
**maplibre-gl-js version:**  2.4.0

**browser:** Chrome 114.0.5735.90 (MacOS)

### Steps to Trigger Behavior

On a map with 3D rendering enabled with RGB tiles.
To reproduce this, let's say we run in a loop an animation for a duration of 6 seconds, but then stop it after 1 second and repeat the process.
That way I can create a "smooth" animation along a path, but there is a culprit after each map.stop() call. There is a little/moderate "jump" in the camera position. That makes the animation clunky. The "jump" seems to be heavier on mountainous area.

### Link to Demonstration

Here is a video of the issue :
[example-jumpy-animation.mov](https://securestorage.geolives.com/maplibre/example-jumpy-animation.mov)

### Expected Behavior
The camera doesn't "jump" after each map.stop() call.

### Actual Behavior
The camera "jumps" after every map.stop() call.

---
I searched over the Github issues and I found these 2 issues that can explains this "jump" between each camera animations. Can somebody confirms that is bound to one of these issues ?
https://github.com/maplibre/maplibre-gl-js/issues/1492
https://github.com/maplibre/maplibre-gl-js/issues/1596

**Comment by HarelM** [comment] 2023-06-15 13:22
Yes, it's a problem which we currently don't have a good solution for.
The problem is that when moving the map we change the elevation of the camera, but there's a need to adjust it when the movement stops.
I think it is related to #1492 and also #2094
Feel free to investigate the best way to solve this...

**Comment by birkskyum** [comment] 2023-07-03 13:18
Is this resolved by https://github.com/maplibre/maplibre-gl-js/pull/2772?

**Comment by HarelM** [comment] 2024-02-26 08:56
I believe this is covered by other issues.
Closing as duplicate.
If this is not the case feel free to comment here and I'll reopen.

**Closed by HarelM** 2024-02-26 08:56 UTC
