### ISSUE TITLE
Occlusion issue with ThreeJS

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [maplibre/maplibre-gl-js#755] opened 2022-01-04 13:54 UTC
Maplibre and Three JS integration has problems with wrong occlusion.

**maplibre-gl-js version**: 1.15.2

**browser**: All

### Steps to Trigger Behavior

 1. Go to https://maplibre.org/maplibre-gl-js-docs/example/add-3d-model/
 2. Rotate the view to align The street "Mars Street" Behind the antenna 3d Model.
 3. See occlusion issue with maplibre street incorrectly occluding the Three JS model:
 
<img width="1504" alt="Screenshot 2022-01-04 at 13 49 11" src="https://user-images.githubusercontent.com/94416008/148068866-ea66239b-e6c1-4737-8db4-956c5fefe4b2.png">

Note that the inverse problem also exists, with cases where Maplibre incorrectly does NOT occlude Three JS model when it should (private code here, but I can share if needed)

<img width="839" alt="Screenshot 2021-12-24 at 21 27 07" src="https://user-images.githubusercontent.com/94416008/148069161-d8e35ce7-18e1-4808-a454-f751fae89fa2.png">

### Link to Demonstration

https://maplibre.org/maplibre-gl-js-docs/example/add-3d-model/

### Expected Behavior

Correct occlusion between ThreeJS scene and Maplibre scene objects

### Actual Behavior

Incorrect occlusion, maplibre

**Comment by Mariussu** [comment] 2022-02-12 12:51
+1
Would love to use MapLibre, but can't until this has been fixed.

**Comment by Mariussu** [comment] 2022-02-12 13:09
https://user-images.githubusercontent.com/73180964/153712691-ac91d437-e6db-4bb0-bfb0-8f314c974e88.mp4

Also the model does not seem to stay still when zooming in or out

**Comment by timokorkalainen** [comment] 2022-03-16 22:50
The jitter first appears in version 2.0.0-pre.1 while version 1.15.2 works perfectly with the Three.js example. It does not however affect the occlusion issue, so I suppose a separate issue should be filed.

**Comment by johnbarratt** [comment] 2022-03-16 23:47
> Also the model does not seem to stay still when zooming in or out

The jitter can be fixed by adding a missing parameter to line 730 of src/geo/transform.ts :
`mat4.scale(m, m, vec3.fromValues(1, 1, mercatorZfromAltitude(1, this.center.lat) * this.worldSize),1));`

**Comment by Mariussu** [comment] 2022-03-17 14:46
Is the occlusion bug simply that 'road_area_bridge' is passed in as parameter to map.addLayer in the example?
This means that the 3d layer will be rendered below the 'road_area_bridge' layer (and all layers above it).

**Comment by Mariussu** [comment] 2022-03-17 14:47
@timokorkalainen I can see you already found https://github.com/maplibre/maplibre-gl-js/issues/1105#issue-1172443738 :+1:

**Comment by timokorkalainen** [comment] 2022-03-17 15:23
> Is the occlusion bug simply that 'road_area_bridge' is passed in as parameter to map.addLayer in the example? This means that the 3d layer will be rendered below the 'road_area_bridge' layer (and all layers above it).

Seems to be correct.

So maybe not actually related to the original issue of combining depth from different "3d/extrude/terrain?" layers.

**Comment by timokorkalainen** [comment] 2022-03-19 10:11
> > Is the occlusion bug simply that 'road_area_bridge' is passed in as parameter to map.addLayer in the example? This means that the 3d layer will be rendered below the 'road_area_bridge' layer (and all layers above it).
> 
> Seems to be correct.
> 
> So maybe not actually related to the original issue of combining depth from different "3d/extrude/terrain?" layers.

This issue of layer ordering in the Add 3D Model example

> > Is the occlusion bug simply that 'road_area_bridge' is passed in as parameter to map.addLayer in the example? This means that the 3d layer will be rendered below the 'road_area_bridge' layer (and all layers above it).
> 
> Seems to be correct.
> 
> So maybe not actually related to the original issue of combining depth from different "3d/extrude/terrain?" layers.

A fix for the render order of layers in the Add 3D Model example was merged into the docs: https://github.com/maplibre/maplibre-gl-js-docs/pull/148

This however is of course _not_ a fix to the original issue discussed, the occlusion issue between 3D models and extruded objects.

**Comment by HarelM** [comment] 2022-08-21 13:16
@timokorkalainen @vincent-lecrubier-skydio I don't understand what's the issue here, can you please elaborate?
The original issue in the docs was solved and I'm not sure what's the issue that remains now...
A jsbin with a problematic example would help a lot here :-)

**Comment by timokorkalainen** [comment] 2022-09-25 18:41
This issue is that draw order is based only on the layer order not actual z-buffer based depth testing.

So even if due to camera perspective the buildings between the camera and the 3D model should be rendered on top of the 3D model, the 3D model is rendered on top of them, if layer ordering defines so.

**Comment by birkskyum** [comment] 2023-05-20 11:31
The initial example in the docs seem to be working. @vincent-lecrubier-skydio  If there is a closed source reproduction that can be reduced and put online as an example, we'd be able to investigate further.

**Closed by birkskyum** 2023-05-20 11:31 UTC
Labels: bug, reproduction-needed
