### ISSUE TITLE
map.fitBounds does not work properly when terrain and moving a large distance 

### ISSUE THREAD

**Issue by llambanna** [maplibre/maplibre-gl-js#2096] opened 2023-01-24 22:22 UTC
**maplibre-gl-js version**: 2.4.0, 3.0.0-pre.3 provided you do not include center and zoom and map is large

**browser**: chrome Version 109.0.5414.87 (Official Build) (x86_64)

### Steps to Trigger Behavior

in 2.4.0:
 1. have terrain and hillshade 
 2. call `fitBounds` to location other side of AM with `animate: false` _or_ with a short duration on animate

in 3.0.0-pre3:
 1. have terrain and hillshade 
 2. do not include center and zoom - a different bug happens if you do
 3. call `fitBounds` to location other side of AM with `animate: false` _or_ with a short duration on animate

### Link to Demonstration

click fit to NZ

#### ML2
with no animate:
https://jsbin.com/yerimatadi/edit?html,output

with short duration:
https://jsbin.com/helulihuqe/edit?html,output

#### ML3.0.0-pre3
with no animate:
https://jsbin.com/qukodoveve/edit?html,output

with short duration: 
https://jsbin.com/dasefuvigu/edit?html,output

### Expected Behavior

it zooms to NZ

#### ML2

it zooms to the left of where it should be no matter the size of the map
<img width="755" alt="Screenshot 2023-01-25 at 11 03 19 AM" src="https://user-images.githubusercontent.com/8648044/214431175-c6d9cacb-5378-442b-b41c-caef8af23a79.png">

#### ML3.0.0-pre3

if map is small it zooms to NZ, if map is large, it doesn't

small map e.g. width: 854px height: 830px:

<img width="1727" alt="Screenshot 2023-01-25 at 11 18 34 AM" src="https://user-images.githubusercontent.com/8648044/214433845-5fa3ace5-4112-4be2-980e-239dc522c112.png">

large map e.g. width: 996px height: 1330px:

<img width="2042" alt="Screenshot 2023-01-25 at 11 16 05 AM" src="https://user-images.githubusercontent.com/8648044/214433466-817acec3-ac84-4d1e-bc98-84f54204b965.png">

**Comment by HarelM** [comment] 2023-01-26 21:17
Isn't this some sort of duplicate of #1937? Look at the comments at the bottom of the issue...

**Comment by llambanna** [comment] 2023-01-29 18:15
@HarelM i'll update my issue - i've worked out it's not to do with AM but to do with moving a large distance in a short period of time. 

i've added in an example with a short duration and on my machine it stops on the way to the bounds

**Comment by llambanna** [comment] 2023-02-12 21:20
@HarelM 

suggestion:
remove ability to have `animate: false` for `fitBounds` because it doesn't work correctly if distance fitting bounds to is too great, for e.g. half the world

there is after all `jumpTo` which can be used this way:
```
const centreZoomBearing = map.cameraForBounds(bounds);
map.jumpTo(centreZoomBearing);
```

**Comment by HarelM** [comment] 2023-02-12 21:23
Not sure I fully understand the suggestion, but API wise, this needs to be the same no matter what are the parameters, it needs to work as expected on the other hand obviously 😀

**Comment by HarelM** [comment] 2023-11-19 16:17
I think this was recently solved:
- #3312 

If not, please let me know and I'll re-open this issue.

**Closed by HarelM** 2023-11-19 16:17 UTC
Labels: bug, need more info
