### ISSUE TITLE
Safari 14 support broken for satellite maps? -> error: Can't find variable: ImageBitmap

### ISSUE THREAD

**Issue by sven-meyer-wetter-com** [maplibre/maplibre-gl-js#2940] opened 2023-08-02 08:35 UTC
If I remember correctly, this worked with maplibre 2.x. Is Safari 14 no longer supported with version 3.x? Or is this an regression? Safari 14.x does not support WebGL2, but MapLibre v3.1 added a WebGL1 fallback. So I assume it should work.

**maplibre-gl-js version**: 3.2.1

**browser**: Safari 14.x and mobile Safari 14.x

### Steps to Trigger Behavior

 1. Just visit https://maplibre.org/maplibre-gl-js/docs/examples/satellite-map/ on one of the above mentioned browsers
 2. error: Can't find variable: ImageBitmap displayed in Console
 3. displayed map contains city names, but not the satellite images as a background

### Link to Demonstration

https://maplibre.org/maplibre-gl-js/docs/examples/satellite-map/

### Expected Behavior

Satellite images as map background are displayed

### Actual Behavior

Satellite images as map background are missing

**Comment by HarelM** [comment] 2023-08-02 09:18
I don't have Safari 14 to test against, but as far as I can see in the code there is no unguarded `createImageBitmap` call and no usage of `new ImageBitmap(...)` so this is strange.
Can you try and run a dev version of the code and reproduce this error to send the stack trace?
You can use a jsbin with the published https://unpkg.com/browse/maplibre-gl@3.2.1/dist/maplibre-gl-dev.js file.
Thanks!

**Comment by IvanSanchez** [comment] 2023-08-02 13:26
This behaviour can be reproduced in any browser by unsetting `ImageBitmap`, like:

```
ImageBitmap = undefined;
const map = new maplibregl.Map({
        style: 'https://api.maptiler.com/maps/hybrid/style.json',
  // etc
```

The problem is at https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/src/util/image_request.ts#L12 , which gets transpiled into `if (data instanceof HTMLImageElement || data instanceof ImageBitmap)`.

Specifically, the `instanceof` operator throws an error when used with an `undefined` second operand.

**Comment by HarelM** [comment] 2023-08-02 17:44
This is extremely strange - this is a type, it shouldn't transpile into actual JavaScript code...

**Comment by neodescis** [comment] 2023-08-03 17:32
Actually, I believe the line is this one:  https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/src/util/image_request.ts#L205

Also, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap), it seems that ImageBitmap is only supported in Safari 15.x and up.

**Comment by HarelM** [comment] 2023-08-03 17:34
Ahh, yes this is likely the root cause, it's an easy fix though. I'll be happy to review a PR that fixes it.

**Comment by HarelM** [comment] 2023-08-05 20:30
I've opened a PR to fix this. Hopefully should be merged and released soon.

**Closed** 2023-08-06 09:47 UTC
Labels: bug, good first issue, PR is more than welcomed
