### ISSUE TITLE
The "Add live realtime data" example is broken

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#3017] opened 2023-08-21 09:52 UTC
**maplibre-gl-js version**: N/A

**browser**: All

### Steps to Trigger Behavior
Open the [Add live realtime data](https://maplibre.org/maplibre-gl-js/docs/examples/live-geojson/) example.

### Expected Behavior
A moving icon should be displayed and tracked.

### Actual Behavior
Nothing is shown on top of the background map.

This is probably because the source GeoJSON at https://wanderdrone.appspot.com/ is no longer available.

![image](https://github.com/maplibre/maplibre-gl-js/assets/1304610/0971e4cc-9f5c-4cd8-a13c-6b1c4ff4ce13)

**Comment by HarelM** [comment] 2023-08-21 11:10
Duplicate of #2833
Feel free to comment there if the example is needed, and if so, what's the essence of it and if there isn't a different example that serves the same need.

**Closed by HarelM** 2023-08-21 11:10 UTC
