### ISSUE TITLE
When enabling the terrain, the image source was cropped.

### ISSUE THREAD

**Issue by huanglii** [maplibre/maplibre-gl-js#5190] opened 2024-12-12 06:18 UTC
**maplibre-gl-js version**: 4.7.1

**browser**: Microsoft Edge 版本 129.0.2792.89 (正式版本) (64 位)

### Steps to Trigger Behavior

 1. Add a image source layer.
 2. Enable terrain.

### Link to Demonstration

https://jsbin.com/yudafux/edit?html,output

### Expected Behavior

![Image](https://github.com/user-attachments/assets/51a5a921-0e08-4afd-bbca-68cf4f4e9b6a)

### Actual Behavior

![Image](https://github.com/user-attachments/assets/df472a5e-9a0a-417b-96fa-54a92b75542d)

**Comment by HarelM** [comment] 2024-12-12 06:45
I believe this is a duplicate of #1559

**Closed by HarelM** 2024-12-12 06:45 UTC
