### ISSUE TITLE
Image layer

### ISSUE THREAD

**Issue by sylvain258** [maplibre/maplibre-gl-js#5149] opened 2024-12-03 12:26 UTC
Hello,

- I have tried displaying  an image layer, but it doesn't render completely. It's a problem that doesn't exist with Mapbox.

**maplibre-gl-js version**:
Latest version

**browser**:
Google Chrome

### Steps to Trigger Behavior

 1. I have declared a source and a layer "image" like that : 
`
map.addSource("image", {
        "type": "image",
        "url": "myimage.png",
        "coordinates": [
            [-0.7559135636273542, 45.20177857982653],
            [-0.7527986751390225, 45.20177857982653],
            [-0.7527986751390225, 45.20010722034934],
            [-0.7559135636273542, 45.20010722034934]
        ]
    }); `

   ` map.addLayer({
        "id": "overlay",
        "source": "image",
        "type": "raster",
        "paint": {
            "raster-opacity": 0.85
        }
    });
`
 2. Result is : ![Image](https://github.com/user-attachments/assets/e6625ae9-ca00-4831-acce-73623b032b93)
 3. The console returns nothing. No error.
 4. No difference if the image is PNG or JPEG.

Thank you very much for your help, 

Sylvain Becquaert

**Comment by HarelM** [comment] 2024-12-03 12:45
The template is here for a reason. Can you please fill it up?

**Comment by sylvain258** [comment] 2024-12-03 14:00
@HarelM I've edited my post. Is this better ?

**Comment by HarelM** [comment] 2024-12-03 21:50
Can you please provide a jsbin/codepen/stackblitz with a way to reproduce your problem? Preferably with as little as possible layers and minimal style?

**Comment by sylvain258** [comment] 2024-12-04 12:04
I found why that doesn't work. It's because I have also a raster dem. When I remove this dem, the problem disappears.

This is the Stackblitz project. If raster dem layer is removed, it works.
[https://stackblitz.com/edit/vitejs-vite-ggixgq?file=index.html](https://stackblitz.com/edit/vitejs-vite-ggixgq?file=index.html)

**Comment by HarelM** [comment] 2024-12-04 13:25
I believe this is a duplicate of #1559 and/or #4088.

**Closed by HarelM** 2024-12-04 13:25 UTC
Labels: need more info
