### ISSUE TITLE
Could I set height for symbol?

### ISSUE THREAD

**Issue by WuMianzhi** [maplibre/maplibre-gl-js#4879] opened 2024-10-23 02:26 UTC
User Story
As a map developer, I can set the height (altitude) of symbols on the map in MapLibre GL JS, so that they accurately represent 3D data and appear correctly in relation to terrain or other 3D elements.

Rationale
This feature is needed to represent points of interest or symbols at varying altitudes, especially in 3D or terrain-based maps where elevation is critical.
Example use cases include marking features like buildings, towers, or mountain peaks with accurate height to provide better spatial awareness to users.
Currently, MapLibre GL JS does not natively support setting symbol heights in 3D space.
Impact
If this feature is not implemented, developers will face difficulties in visualizing accurate altitude-based data, especially in 3D mapping applications.
This could lead to inaccurate or flat representations of data, reducing the quality and usability of maps built with MapLibre GL JS for certain applications like terrain modeling, urban planning, or geospatial analytics.

**Comment by HarelM** [comment] 2024-10-23 10:29
There is a discussion around it here: 
https://github.com/maplibre/maplibre-style-spec/issues/62

Is this a duplicate of the other?

**Comment by WuMianzhi** [comment] 2024-10-25 02:33
yes, im sorry

**Closed** 2024-10-25 02:33 UTC
Labels: need more info
