### ISSUE TITLE
on load method： Occasionally the load method does not trigger a callback

### ISSUE THREAD

**Issue by qlanto224** [maplibre/maplibre-gl-js#4024] opened 2024-04-23 01:37 UTC
**maplibre-gl-js version**:4.1.3 and 2.4.0

**browser**:

### Steps to Trigger Behavior
1. open https://codepen.io/oberhamsi/pen/ZENLQEN
2. Look in the console for the loaded text - no loaded text meaning no load event and map is no loaded. 

### Link to Demonstration

https://codepen.io/oberhamsi/pen/ZENLQEN

### Expected Behavior
Loaded event is fired or the map is loaded

### Actual Behavior
Niether

**Comment by qlanto224** [comment] 2024-04-23 02:57
when I click map ， the load method trigger

**Comment by HarelM** [comment] 2024-04-23 04:38
Please provide a jsbin with a reproduction.

**Comment by qlanto224** [comment] 2024-04-23 06:38
> Please provide a jsbin with a reproduction.

sorry， I cant provide this style.  
I found that when the requested layer data is too large, the request time is more than 10 seconds, it will not be called.
I'm not sure if there is a timeout inside 'load'.

**Comment by HarelM** [comment] 2024-04-23 08:50
I'm not aware of timeout definition. 
Also, without a reproduction I can't help. 
You don't have to provide your style, but rather something that reproduces the issue...

**Comment by qlanto224** [comment] 2024-04-23 08:57
```js
import { Map } from 'maplibre-gl';
import { useEffect, useRef } from 'react';
export default () => {
  const mapRef = useRef<any>(null);
  useEffect(() => {
    const style ;// this style have some slow-requested data sources
    let map = new Map({
      container: mapRef.current,
      antialias: true,
      maxPitch: style.maxPitch ? style.mapPitch : 72,
      minZoom: style.minZoom,
      hash: false,
      attributionControl: false,
      maplibreLogo: true,
      logoPosition: 'bottom-right',
      style: style,
    });
    document
      .getElementsByClassName('maplibregl-ctrl-logo')[0]
      .removeAttribute('href');
    map.setRenderWorldCopies(false);
    map.on('load', () => {
      console.log('load finish');
    });
  }, []);
  return <div style={{ width: '100%', height: '50vh' }} ref={mapRef}></div>;
};
```
example：
![image](https://github.com/maplibre/maplibre-gl-js/assets/58463221/b23f2e74-7cf3-4d25-a6b1-5dc98dd43bb3)

**Comment by qlanto224** [comment] 2024-04-24 13:10
> I'm not aware of timeout definition. Also, without a reproduction I can't help. You don't have to provide your style, but rather something that reproduces the issue...

This phenomenon mainly occurs when the browser refreshes.
this is my code：
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Draw GeoJSON points</title>
    <meta property="og:description" content="Draw points from a GeoJSON collection to a map." />
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='https://unpkg.com/maplibre-gl@4.1.3/dist/maplibre-gl.css' />
    <script src='https://unpkg.com/maplibre-gl@4.1.3/dist/maplibre-gl.js'></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
    </style>
</head>
<body>
<div id="map"></div>
<script>
  $.ajax({
  url: url,
  success: function(style) {
    const map = new maplibregl.Map({
        container: 'map',
        style:style,
    });
    map.on('load', (e) => {
      console.log(e)
      console.log('load')
    });
  },
});
</script>
</body>
</html>

```

**Comment by qlanto224** [comment] 2024-04-24 13:20
This is a video I made of the operation.


https://github.com/maplibre/maplibre-gl-js/assets/58463221/3b61a720-b11d-45c0-9aa1-7c4d3c68258b

**Comment by HarelM** [comment] 2024-04-27 04:33
Can you check if the map `isLoaded` before you register the callback?
It might be that when you refresh the browser and everything is cached the map initialization finishes before you register the callback (classic race condition).

**Comment by qlanto224** [comment] 2024-04-27 06:18
> Can you check if the map `isLoaded` before you register the callback? It might be that when you refresh the browser and everything is cached the map initialization finishes before you register the callback (classic race condition).
like this? I'm not sure if that's the check
```js
let a = setInterval(()=>{
    if(map.loaded()){
      map.on('load', (e) => {
        console.log('load')
      });
      clearInterval(a)
    }
  },50);
```

**Comment by qlanto224** [comment] 2024-04-27 06:19
> Can you check if the map `isLoaded` before you register the callback? It might be that when you refresh the browser and everything is cached the map initialization finishes before you register the callback (classic race condition).

I'm not sure if that's the check. 
like that:
```js
let a = setInterval(()=>{
      if(map.loaded()){
        map.on('load', (e) => {
          console.log('load')
        });
        clearInterval(a)
      }
    },50);
```

**Comment by HarelM** [comment] 2024-04-27 07:06
If map is loaded you won't get the load event.
```
if (map.isLoaded()) doSomeThing()
map.on('load', doSomeThing)
```

**Comment by qlanto224** [comment] 2024-04-27 07:33
I tried, but `map.loaded()` condition also can't execute.

```js
// create map
// dosomthing
if (map.loaded()) {
    console.log('loaded----'+performance.now());
}else{
    console.log('load');
   // Execution stops at this point
    map.on('load', function() {
    console.log('load----'+performance.now());
});
```
can console'load' ,but can't console 'load---time'

**Comment by HarelM** [comment] 2024-04-27 08:25
I don't understand what you wrote, but I think this is working as expected, I'm inclined to close this issue...

**Comment by qlanto224** [comment] 2024-04-27 08:37
> I don't understand what you wrote, but I think this is working as expected, I'm inclined to close this issue...

I say ， 
When the map is not loaded, the `on('load')` method is still not executed. Because `map.loaded()` is true. And there's no `map.isLoaded()` method, just `map.loaded()`.
```js
if (map.isLoaded()) doSomeThing()
map.on('load', doSomeThing)
```

**Comment by qlanto224** [comment] 2024-04-27 08:39
sorry, English is not very well. But I'm not sure what you don't understand.

**Comment by HarelM** [comment] 2024-04-28 21:04
I wrote the following code but I'm unable to reproduce your issue:
```
fetch('https://demotiles.maplibre.org/style.json')
        .then(response => response.json())
        .then(data => {
            const map = new maplibregl.Map({
                container: 'map', // container id
                style: data,
                center: [0, 0], // starting position [lng, lat]
                zoom: 1, // starting zoom
                maplibreLogo: true
            });
            if (map.loaded()) console.log('Map already loaded');
            map.on('load', () => {
                console.log('Map loaded, load event');
            });
        });
```
I always get `Map loaded, load event`.

**Comment by qlanto224** [comment] 2024-04-29 01:14
> I wrote the following code but I'm unable to reproduce your issue:
> 
> ```
> fetch('https://demotiles.maplibre.org/style.json')
>         .then(response => response.json())
>         .then(data => {
>             const map = new maplibregl.Map({
>                 container: 'map', // container id
>                 style: data,
>                 center: [0, 0], // starting position [lng, lat]
>                 zoom: 1, // starting zoom
>                 maplibreLogo: true
>             });
>             if (map.loaded()) console.log('Map already loaded');
>             map.on('load', () => {
>                 console.log('Map loaded, load event');
>             });
>         });
> ```
> 
> I always get `Map loaded, load event`.

sure , I found . when then `zoom` set `11`, can't get that.  Maybe `404 or other ajax error` occurred due to resource loading.

**Comment by HarelM** [comment] 2024-04-29 05:45
Since I can't reproduce the issue myself and you can't provide a scenario that reproduces the issue, you'll need to figure out how to solve this. Good luck!

**Comment by HarelM** [comment] 2024-05-29 11:46
I can't stress this enough, saying something is not working without linking a reproducible example is not so helpful...
There's still no jsbin/codepen or anything else in this thread to this day...

**Comment by oberhamsi** [comment] 2024-05-29 12:37
sorry about that - here's a bin https://codepen.io/oberhamsi/pen/ZENLQEN i can repro this on FF&chrome. 

in may bigger app it does not happen so consistently. when i inspect the map instance, it has `loaded()===true` but `load` never fired. clicking the map instantly fires `load` and everything works. i tried debug stepping into why that is and it seems to start from here https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map.ts#L3184

**Closed** 2024-06-21 07:33 UTC
Labels: bug, PR is more than welcomed

**Comment by cneben** [comment] 2024-07-14 22:47
Same problem is reproducible on master here: https://github.com/cneben/react-maplibre-standalone on('load') handler is never called. It was working fine with maplibre v3, probably an error while loading style. Investigating.
