### ISSUE TITLE
Jump at the end of a pan when both terrain and transformCameraUpdate are used

### ISSUE THREAD

**Issue by UberMouse** [maplibre/maplibre-gl-js#4377] opened 2024-07-08 21:45 UTC
**maplibre-gl-js version**: 4.3.2 (still present in 4.5.0)

**browser**: Any

### Steps to Trigger Behavior

 1. pan with the mouse
 2. observe the fact the camera has been teleported to narnia
 3.

### Link to Demonstration

https://codepen.io/UberMouse/pen/BagaOWX

### Expected Behavior

A normal pan happens, the same as when `transformCameraUpdate` is not set

### Actual Behavior

A large jump in the camera position happens when `transformCameraUpdate` is set to even an identity function

This must be caused by #4132

**Comment by chrneumann** [comment] 2024-07-09 08:30
Duplicate of #4233

**Comment by chrneumann** [comment] 2024-07-09 08:34
Did you find a workaround (as you pointed to #4132)? A fix would be great. A unit test for the bug is at #4299.

**Comment by HarelM** [comment] 2024-07-09 09:05
Closing as duplicate, let's keep the conversation in the other issue please.

**Closed by HarelM** 2024-07-09 09:05 UTC

**Comment by UberMouse** [comment] 2024-07-09 10:46
>Did you find a solution (as you pointed to #4132)?

I did not. That PR was just the only change in 4.3.2 and 4.3.1 does not exhibit the issue.
