### ISSUE TITLE
Mapbox Draw unclickable buttons

### ISSUE THREAD

**Issue by fidzee** [maplibre/maplibre-gl-js#2705] opened 2023-06-19 18:00 UTC
Since a recent update, the polygon and trash buttons from mapbox draw haven't been clickable whenever added to a maplibre-gl map.

this bug also happens on the documentation's website for maplibre-gl. I'm not sure which side of things this bug is from.

Here's the behavior on a maplibre map
https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/

Compared to the normal behavior for mapbox map 
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

they use the same code to initialize the buttons: 

```
var draw = new MapboxDraw({
displayControlsDefault: false,
controls: {
polygon: true,
trash: true
}
});
map.addControl(draw);
 
map.on('draw.create', updateArea);
map.on('draw.delete', updateArea);
map.on('draw.update', updateArea);
```

A little note: updating the mapbox-draw to 1.4.1 shows the polygon and trash icons instead of line, but are still not clickable

**Comment by HarelM** [comment] 2023-06-19 19:08
Duplicate of #2601

**Closed by HarelM** 2023-06-19 19:08 UTC
