### ISSUE TITLE
Scaling of 3d buildings doesn't work as expected

### ISSUE THREAD

**Issue by marr** [maplibre/maplibre-gl-js#3157] opened 2023-10-02 17:33 UTC
I noticed the example here https://maplibre.org/maplibre-gl-js/docs/examples/3d-buildings/ is supposed to have the building heights transition as you zoom. It doesn’t appear to happen.

There is a similar example on mapbox's site that does work: https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/

**maplibre-gl-js version**: @latest

**browser**: Chrome / OSX

### Steps to Trigger Behavior

 1. Visit the example link.
 2. Zoom in/out with mousewheel.
 3. Notice that the buildings "pop" in and out during zoom, rather than scale in/out.

### Link to Demonstration

https://maplibre.org/maplibre-gl-js/docs/examples/3d-buildings/

**Comment by sebastianoscarlopez** [comment] 2023-10-02 17:55
The buildings are being seen because of the style.json, this is not because of the added layer on the load event as supposed to be.
The line ['get', 'height'] should by ['get', 'render_height']

Could I take this issue?

**Comment by HarelM** [comment] 2023-10-02 18:44
Sure.

**Comment by sebastianoscarlopez** [comment] 2023-10-04 13:21
I submitted PR #3165 with the solution.

I tried to put some colors in, keeping the opacity but I ran into an error. At first, I thought there was something wrong with the cape that caused some kind of z-fight, but now I think that's a mistake.

Here you have a Codepen to reproduce it, if we set opacity = 1 we have a typical z-fighting where two or more faces have the same position, but. . . let's say we put opacity = 0.6 it looks like a z fight with the ground, I know it doesn't make sense, I'm just saying that's how it looks.

https://codepen.io/sebastianoscarlopez/pen/ZEVMLaV?editors=1000

**Comment by acalcutt** [comment] 2023-10-04 16:47
what is the error? your example with opacity = 0.6 looks fine to me.

**Comment by sebastianoscarlopez** [comment] 2023-10-04 18:22
Doing zoom out/in we see something like this

<img width="756" alt="image" src="https://github.com/maplibre/maplibre-gl-js/assets/10349981/ae16a4a8-ef18-4d9c-b60b-3a2318ab2195">

**Comment by sebastianoscarlopez** [comment] 2023-10-06 15:17
Here is the issue with a simple square extrusion.
Fails with Chrome or Safari on mac, it looks go on Linux and Windows with all the browsers, also works fine with Edge on mac.
https://jsbin.com/wohikapizo/edit?html,output

https://github.com/maplibre/maplibre-gl-js/assets/10349981/c4107aab-9a6d-40fc-b106-f7c44c80ffb9

**Comment by HarelM** [comment] 2023-10-06 20:13
I'm not sure this is the same issue as reported originally.
I would consider opening a new issue and closing this one as solved now that a new version was released...

**Comment by AbelVM** [comment] 2023-10-06 21:11
Linux here, and...
![image](https://github.com/maplibre/maplibre-gl-js/assets/9017165/127d7557-04d2-4b3d-a538-5a5ac3be49b0)

But in my tests looks like it's related to mashed-up buildings with different color encoding that share a portion of the facade, and they show that glitching halftone. 

Might it be related to different buildings with the same footprint? Shared facades fighting to be shown?

**Comment by sebastianoscarlopez** [comment] 2023-10-07 02:49
@HarelM yes

> I'm not sure this is the same issue as reported originally. I would consider opening a new issue and closing this one as solved now that a new version was released...

Yes, please close this one and we can continue the discussion in #3187

**Closed** 2023-10-07 03:24 UTC
