### ISSUE TITLE
Wrong WebGL detection with modern Chrome and MapboxGL texts in the warning

### ISSUE THREAD

**Issue by AbelVM** [maplibre/maplibre-gl-js#1324] opened 2022-06-28 09:23 UTC
Jump to any example, like https://maplibre.org/maplibre-gl-js-docs/example/game-controls/ with **Chrome 103.x** and you will get 

![gnome-shell-screenshot-b65pil](https://user-images.githubusercontent.com/9017165/176143420-d8bc6fba-603e-49d1-ac0e-3051c777c22a.png)

Two issues here:
* This version of Chrome aboslutely supports WebGL
* There are `mapboxgl` leftovers in the warning text

**Comment by wipfli** [comment] 2022-06-28 10:26
I am not able to reproduce this problem. I use Version 103.0.5060.53 (Official Build) (64-bit) of Chrome on Ubuntu. Is maybe webgl turned off for some reason in your browser?

![image](https://user-images.githubusercontent.com/53421382/176157082-e3ac543e-40c5-4ea6-92be-a054e8aa9982.png)

**Comment by AbelVM** [comment] 2022-06-28 10:50
Same OS, same Version, and same flags status. Checking https://get.webgl.org/, the cube spinnes :sweat_smile: 
![image](https://user-images.githubusercontent.com/9017165/176161009-2a082137-8ac1-433d-85b7-99ddcdcffb7b.png)

Background map in https://maplibre.org is working as expected :thinking: 

Anyway, the `mapboxgl` leftovers in the texts should be checked
![image](https://user-images.githubusercontent.com/9017165/176161412-406454cd-b46e-4307-8448-317a391ea3ac.png)

**Comment by wipfli** [comment] 2022-06-28 11:46
#947

**Comment by wipfli** [comment] 2022-06-28 11:47
What is you exact browser version and OS?

**Comment by AbelVM** [comment] 2022-06-28 12:19
* Ubuntu 22.04 (X11, amd64)
* Chrome Version 103.0.5060.53 (Official Build) (64-bit) `chrome://gpu`
![image](https://user-images.githubusercontent.com/9017165/176176637-74c0f917-02db-479b-9dc3-b5f88ba59ee2.png)

**Comment by HarelM** [comment] 2022-08-21 18:37
@AbelVM is this still an issue? Can we close this one?

**Comment by AbelVM** [comment] 2022-08-22 06:10
Good to close! Thanks!

**Closed** 2022-08-22 06:33 UTC
Labels: bug, need more info
