### ISSUE TITLE
map.on(type,layer,()=>{}) does not work. Angular project.

### ISSUE THREAD

**Issue by TomasTubertSFC** [maplibre/maplibre-gl-js#3396] opened 2023-11-21 08:25 UTC
**maplibre-gl-js version**:3.6.1

**browser**:Chrome

### Steps to Trigger Behavior

 1.Click above cluster

### Expected Behavior 

I want to be able to add an event to the layers. No map.on event works.

Right now the map is initialised in the map.service. The map component after mounting calls the function to initialise it.
The container id="map" is in the layout, in the main.

This has a reason, because I don't want that every time I access the /map path, the component has to be mounted, but I want the map to be initialized.

### Actual Behavior 
Nothing happens. Any layout event works map.on('event',layout)

**Comment by HarelM** [comment] 2023-11-21 08:31
I know for a fact this works in ngx-maplibre, our supported angular wrapper, so I guess the problem is with your code...

**Comment by TomasTubertSFC** [comment] 2023-11-21 09:17
So you recommend me to use ngx-maplibre insted right?

**Comment by HarelM** [comment] 2023-11-21 09:19
Yup

**Comment by HarelM** [comment] 2024-01-09 20:49
Closing... If there's something else, please ping me and I'll reopen

**Closed by HarelM** 2024-01-09 20:49 UTC
