### ISSUE TITLE
Text on GeoJSON polygon not rendered

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1124] opened 2022-03-24 06:58 UTC
**maplibre-gl-js version**: 3c476e4f814d26e9c761bb7a7db8e7a872f68e5b

**browser**: Chrome

### Steps to Trigger Behavior

 1. Add geojson source with polygon
 2. Add text along line
 3. Use terrain

### Link to Demonstration

https://codesandbox.io/s/charming-blackwell-2hj0wb?file=/index.html

### Expected Behavior

Text renders along polygon. This is the case if terrain is switched off with the little gray square button in the top right corner. Thanks @RNMBuser for the example template!

<img src="https://user-images.githubusercontent.com/53421382/159859568-7e4ae06c-0af0-4f35-801f-521d7311ecae.png" width=350>

### Actual Behavior

Text is not shown

<img src="https://user-images.githubusercontent.com/53421382/159859760-dad796fa-5ebe-44b8-978a-c6fabb134c1a.png" width=350>

**Comment by wipfli** [comment] 2022-03-24 06:58
@prozessor13

**Comment by HarelM** [comment] 2022-03-24 07:58
I know this is a stupid question, but did you check that it's not related to text collision?

**Comment by wipfli** [comment] 2022-03-24 08:01
Was my first thought too. The top-most layer should render and the lower ones should disappear. This is what happens actually when terrain is off.

**Comment by HarelM** [comment] 2022-04-16 12:23
There's a console error related to the ability to load an image, which might cause this rendering problem, not sure.
Can you reproduce it with latest version?

**Comment by wipfli** [comment] 2022-04-17 06:17
Yes @HarelM, the error still persists: https://codesandbox.io/s/sharp-cohen-zk9ny1

**Comment by HarelM** [comment] 2022-04-18 19:05
According to my debug the following is the code that causes the issue I believe:
https://github.com/maplibre/maplibre-gl-js/pull/1022/files#diff-a39025d6bae5c7f234acc580ab732d25a3b4cf3406cf2cda81a5030100f98711R115
And maybe this part as well:
https://github.com/maplibre/maplibre-gl-js/pull/1022/files#diff-a39025d6bae5c7f234acc580ab732d25a3b4cf3406cf2cda81a5030100f98711R148
It seems that there are some conditions related to last layer and previous layer.
If, for example, I add two layers of symbol text (simply duplicate the `maine-text` layer) the text will appear.
I think there was a bug related to last layer etc that introduced this addition in the code, but I'm not sure how to properly solve this.
@prozessor13 this does however feels to me like a blocker, what do you think?

**Comment by prozessor13** [comment] 2022-04-18 20:21
Yes this looks like a bug, i will look onto it! Thx for preparation!

**Comment by HarelM** [comment] 2022-05-12 13:52
Fixed by #1189

**Closed by HarelM** 2022-05-12 13:52 UTC
Labels: Terrain 3D, Terrain 3D Blocker
