### ISSUE TITLE
How to use ES2015 (ES6) Imports to allow Tree Shaking?

### ISSUE THREAD

**Issue by janwendt** [maplibre/maplibre-gl-js#2862] opened 2023-07-12 09:12 UTC
**maplibre-gl-js version**: 3.0.1

**browser**: Firefox 113.0.2

How can i use ES2015 (ES6) Imports to reduce Bundle Size via Tree Shaking (https://webpack.js.org/guides/tree-shaking/)?
I would like to use something like this:
```
import { Map } from "maplibre-gl";
```
instead of
```
import "maplibre-gl";
```
because this general import increases my bundle size by about 740 KB. I have not found anything about this in the documentation.

With Minisearch for example I can use this import
```
import MiniSearch from 'minisearch';
```
and tree shaking works immediately because ES2015 (ES6) imports are supported.

**Comment by HarelM** [comment] 2023-07-12 10:19
I don't think you can... Since maplibre uses workers and their code is also bundled, you can't easily import just part of the library...
I think this issue is a duplicate of #977.

**Closed** 2023-07-14 17:23 UTC
