### ISSUE TITLE
Backport fix for iOS 15 Safari from Mapbox-GL-JS version 1.13.2

### ISSUE THREAD

**Issue by SuperPat45** [maplibre/maplibre-gl-js#472] opened 2021-10-13 18:26 UTC
Mapbox-GL-JS release version 1.13.2 with this fix for iOS 15 Safari: https://github.com/mapbox/mapbox-gl-js/pull/11084
Maplibre could include it.

**Comment by SuperPat45** [comment] 2021-10-21 19:50
This fix break panning with the map(box|libre)-gl-leaflet plugin: https://github.com/mapbox/mapbox-gl-leaflet/issues/145

**Comment by wipfli** [comment] 2022-05-21 07:27
@SuperPat45 is leaflet still affected by this fix?

**Comment by manuelroth** [comment] 2022-09-02 10:02
Hi @wipfli and @SuperPat45, I just found this issue because I was able to reproduce this problem while testing out MapLibre on iOS devices. The current situation results in a very bad user experience with MapLibre on iOS devices. My suggestion would be to introduce this fix only in MapLibre v2. So users of mapbox-gl-leaflet could continue to use it with MapLibre v1 without issues. What do you think about that?

**Comment by manuelroth** [comment] 2022-09-02 10:04
[The issue on mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet/issues/145) is still open. Fixing this issue is not a priority for Mapbox as the repository is marked as `Note: this tool is experimental and is not actively supported by Mapbox`. So I think it's best to move forward with this in MapLibre v2.

**Comment by wipfli** [comment] 2022-09-02 11:03
Thanks for the feedback @manuelroth. Can you maybe take the bug report template and write up some more information about the problem? I guess there is some info in the linked repository, but it would be great if we could have it in this thread here directly...

**Comment by manuelroth** [comment] 2022-09-02 12:05
Yes sure. I have created a bug report issue for this problem: https://github.com/maplibre/maplibre-gl-js/issues/1603. Please let me know if there is anything missing.

**Comment by HarelM** [comment] 2023-11-19 15:39
The other issue is closed. closing this one as well.

**Closed by HarelM** 2023-11-19 15:39 UTC
Labels: bug, need more info
